function BHAL_CAN5_outputs(varargin)
%===========$Update Time :  2025-05-28 15:50:33 $=========
disp('Loading $Id: BHAL_CAN5_outputs.m  2025-05-28 15:50:33    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-28 15:50:33 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN5_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidTBOX1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CbnPreACEnaReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PowerOffTSet_cnt'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReOutsideMirror_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReDoorLock_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RePwrReqTbox_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReRadio_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RemoteACTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RemoteAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TBOXNETSIGSTR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TBOXRemotePW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TBOXTESTSTATUS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTBOX2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeSyncFromBSYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTBOX3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChargePercentSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOFFDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOFFHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOFFMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOFFMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOFFYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOnDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOnHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOnMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOnMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReserveChargeOnYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TBOXHWVER_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TBOXSWVER_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
