function BINP_CAN5_outputs(varargin)
%===========$Update Time :  2025-05-28 15:54:12 $=========
disp('Loading $Id: BINP_CAN5_outputs.m  2025-05-28 15:54:12    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-28 15:54:12 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN5_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidTBOX1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidTBOX2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidTBOX3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CbnPreACEnaReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PowerOffTSet_cnt'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReOutsideMirror_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReDoorLock_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_RePwrReqTbox_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReRadio_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RemoteACTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RemoteAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TBOXNETSIGSTR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TBOXRemotePW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TBOXTESTSTATUS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSyncFromBSYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChargePercentSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOFFDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOFFHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOFFMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOFFMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOFFYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOnDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOnHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOnMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOnMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReserveChargeOnYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TBOXHWVER_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_TBOXSWVER_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
