function BACC_outputs(varargin)
%===========$Update Time :  2024-07-22 09:11:37 $=========
disp('Loading $Id: BACC_outputs.m  2024-07-22 09:11:37    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-07-22 09:11:37 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BACC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VACC_HVTHCMSysAvail_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_LVBattVoltSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_VehHVPwrAvail4THCM_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSEnDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACPresWarnSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACTempWarnSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACEnDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACPreSelfChkSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
