function BTQR_outputs(varargin)
%===========$Update Time :  2024-08-28 10:54:43 $=========
disp('Loading $Id: BTQR_outputs.m  2024-08-28 10:54:43    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-28 10:54:43 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTQR_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTQR_FrTMTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_FEDUTMSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_RrTMTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_REDUTMSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_ActualFEDUWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_ActualREDUWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_NoABSFEDUWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_NoABSREDUWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQR_ACCHoldPdovrdInc_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
