function BBCM_outputs(varargin)
%===========$Update Time :  2025-05-19 13:45:35 $=========
disp('Loading $Id: BBCM_outputs.m  2025-05-19 13:45:35    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-19 13:45:35 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BBCM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VBCM_AntitheftSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateRemote_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HornCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AllDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMDoorLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AntitheftSeatFlod_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PsDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RLDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RRDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockSetting_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CrashDetd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DoorLockIND_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_Dimmer_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DimmerEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PosLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrFogLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BrakeLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ReverseLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMBuzzerReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TrunkRel_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateHDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrWiper_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WasherCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WiperFixMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SleepReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LampPwr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SPTGDet_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APSOpenPTG_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FollowMe_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_IVIRST_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CountAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFSWTri_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorFlodPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FuelDoorPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFRDNBrightReq_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGInnerSW2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagHCrash_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrvWdwCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PasWdwCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrRWdwCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PsRWdwCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APMDoorControlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbFunEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbWelEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbDimEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLinkDriSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbPwrWarnEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbODAEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ATCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_fUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_UserNow_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbFunENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbWelENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbDimENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLinkDriStaFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbPwrWarnENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbODAENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardIND_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DimSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PassSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FWipSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FWasSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnSwTSetSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SPTGENFun_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SPTGENFunMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_OutMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnSwTimeSetSta123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnSwTimeSetSta457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDLHandleLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDRHandleLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDHandleCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HBeamADB_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WalkInUnLkENMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WalkOutLkENMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RmLpModeENMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockSettingStaMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FollowMeENMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WalkInUnLkENFunSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WalkOutLkENFunSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RmLpModeENFunSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FollowMeENFunSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HoodRelCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WelcomeLight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGOpenHeightSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_UserHeightSet_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight1_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight2_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight3_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight4_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight5_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGUserHeight7_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGOpenHeight12_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGOpenHeight34_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGOpenHeight57_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SenstivityPosnCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TimeGapLevelSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ACCLevelMem12_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ACCLevelMem34_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ACCLevelMem57_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LRightStaCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LLeftStaCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AutoLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AutoLockMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AutoUnlockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AutoUnlockMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey1FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey2FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey3FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey4FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey5FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey6FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey7FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HMIKey8FuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AutoWipHSpdENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrvWdwReqAP_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PasWdwReqAP_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrRWdwReqAP_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PsRWdwReqAP_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CLWinLockDrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CLWinLockDrStaMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WinLFOpenedSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WinRFOpenedSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WinLROpenedSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WinRROpenedSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
