function BTHC_outputs(varargin)
%===========$Update Time :  2024-06-24 16:38:20 $=========
disp('Loading $Id: BTHC_outputs.m  2024-06-24 16:38:20    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-06-24 16:38:20 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTHC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTHC_FDCompCmd_rpm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV1Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV2Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV3Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEXV1Cmd_step'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEXV2Cmd_step'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOTXVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFWVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDTWVCmd_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrWPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CoolgFanActDuty_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDAGSCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP1Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP2Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP3Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrLeAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrRiAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDRrAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDBlowerCmd_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BatteryMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EDriveMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CabinMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUACLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUAutoLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUACMaxLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUSyncLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigAirIntenZon1St_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigWindDirZon1St_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigRecircSt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon1St_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon2St_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigClntTHvBattOut_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnSolarLeft_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigClntTHvBattIn_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnSolarRight_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigAmbAirT_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnAirT_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACSubMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDRecyAutoCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompDeltaU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Compe_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Blowere_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Vbase_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2P_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2I_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2U_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2e_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCe_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1P_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1I_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1U_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1e_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACModeMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Face_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Foot_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Frost_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FaceM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FootM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUSyncSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACForceOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_RecAutoFlg_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1M_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_fdefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon2StM_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCMAPTCWarningSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
