function BSCP_outputs(varargin)
%===========$Update Time :  2024-07-11 15:09:42 $=========
disp('Loading $Id: BSCP_outputs.m  2024-07-11 15:09:42    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-07-11 15:09:42 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BSCP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VSCP_CAN3GWESC1toNIDECVehSpeedtoNidec_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN3GWIVI6toNIDECIVITimeSecondtoNidec_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN3GWIVI6toNIDECIVITimeMonthtoNidec_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN3GWIVI6toNIDECIVITimeHourtoNidec_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN3GWIVI6toNIDECIVITimeDaytoNidec_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN3GWIVI6toNIDECIVITimeMinutetoNidec_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
