function BINP_CAN4_outputs(varargin)
%===========$Update Time :  2025-05-14 10:42:52 $=========
disp('Loading $Id: BINP_CAN4_outputs.m  2025-05-14 10:42:52    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-14 10:42:52 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN4_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidZFRC1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZFRCE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZRRCE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZRRCE1001_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidzGWCANRr1C500_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ParkBrakeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AirPressureFC2_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMAutoLightSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMBrakeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMHBeamSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMHeadLpSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMLFTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMLightSensorVSta_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMPLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMRFTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMRFogLpSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMSeatbeltSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMWasherSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMWiperASSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMWiperHSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZFRBCMWiperLSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMAllDoorSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AirPressurePC3_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_AirPressureRC1_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FDCCHASSISVCUEACPressSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMCallingSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMLRTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMPLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMRRTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMSTOPSW2Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZRRBCMSTOPSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCOutVolSta_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EACEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EACErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EACInvTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EHPSEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EHPSErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EHPSInvTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EHPSMotorSpdSta_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUACRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUDCDCEACEHPSHVLoopSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUDCDCEACEHPSPreRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUDCDCEACEHPSRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUHVILSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUMCUHVLoopSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUMCUPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUMCUPreRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUSelfChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
