function BHAL_SYS_outputs(varargin)
%===========$Update Time :  2024-07-05 14:34:38 $=========
disp('Loading $Id: BHAL_SYS_outputs.m  2024-07-05 14:34:38    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-07-05 14:34:38 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_SYS_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CarMode1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CarModel2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CarModel3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ECU1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ECU2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Major1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Major2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Minor1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Minor2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Patch1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Patch2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Country1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Country2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Variation_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Dash1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Change1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Change2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Dash2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA5_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA6_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA7_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SHA8_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AcoreReadyToSlp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PwrReq_OTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AllowMovThd_OTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EvccAplusPwrUpReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrivetrainSelect_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ReadFlashCorrect_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAntitheft_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw1'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw2'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw3'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw4'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw5'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw6'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw7'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomnumberY_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashACModeMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFace_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFoot_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFrost_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFaceM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFootM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashCCUSyncSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashACForceOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashsigRecircSt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRecAutoFlg_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAirIntenZone1M_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Flashfdefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashsigSetTempZon1St_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashsigSetTempZon2StM_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashCountAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashMFSWTri_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashMirrorFlodPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashFuelDoorPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLockSetting_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashMFRDNBrightReq_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashWiperFixMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashIVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AnyNMID_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CurrentNmState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_NvmProtectSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AuxBattVolmV_mV'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Pedal1Ref5V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Pedal2Ref5V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EAPS1MINMem_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EAPS2MINMem_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashHoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashTailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashCTDLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashTailgateHDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_NetworkReqCalled_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PmicBootReason_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WisrBootReason_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAPMDoorControlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AcoreRebootCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDGetDynoMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN1BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN2BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN3BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN4BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN5BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_funAuto_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagDRLOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagFMHT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagFLTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagFRTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagRLTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DiagRRTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSConfig_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TireSize_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSFunConfig_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashfUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbFunEN_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbWelEN_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbDimEN_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbLinkDriSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbPwrWarnEN_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbODAEN_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbColorSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashAmbBrightnessSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
