function BTQD_outputs(varargin)
%===========$Update Time :  2025-04-25 11:30:22 $=========
disp('Loading $Id: BTQD_outputs.m  2025-04-25 11:30:22    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-04-25 11:30:22 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTQD_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTQD_GearActualPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkRequest_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PBWLockTO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PBWUnlockTO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDem_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AfterAvailableTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AfterAvailableTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqSourceFr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqSourceRr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUAvailBrkRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUAvailBrkRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqTargetShaftSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LimpHomeAct_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RollRegenEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVDriveMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVDriveModeValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ShiftGearPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PButtonSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrRgnDecrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrRgnDecrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUActTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUActTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDURolRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDURolRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUSpdValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUAvailBrkRgnTqV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUSpdValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUAvailBrkRgnTqV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RgnAbnorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PTCSPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrRgnPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrRgnPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExternalTqAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrIdcMin_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrIdcMax_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrUdcMin_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrUdcMax_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrIdcMin_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrIdcMax_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrUdcMin_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrUdcMax_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CoordWhlTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CoordWhlTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CrashDetd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DiagHCrash_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ReBrakeLPReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LoSpdBrkCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LowIdleAccPedal_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_APSStaSys_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_APSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_APSDecReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_APSDecReq_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExtShftAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EstVehWeightResult_kg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_BOSEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepON_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PreLoadHold_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PreLoadPreEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepPrLoadEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EquivAccPedalSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriveProtEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActParkRequest_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RegenTqLimitEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PedAccTqEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_IVIPwrLockSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExtDoorAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_WhlTqCapGenFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_WhlTqCapGenRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_OPDHoldLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SaveRegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCVCURegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SpdCtrlMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SpdCtrlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SetSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWCCancelSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWCSetdownSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWCResUpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepBaseTqD_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VehActSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RegenLimIndSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_BrkSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWC2CancelSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWC2SetdownSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWC2ResUpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SWC2LADASSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SpdLim4SetSpd_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SetSpdLimWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EPBCarWashMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
