function BHAL_GPIO_outputs(varargin)
%===========$Update Time :  2025-04-18 15:05:25 $=========
disp('Loading $Id: BHAL_GPIO_outputs.m  2025-04-18 15:05:25    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-04-18 15:05:25 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_GPIO_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_AccelPedal1Vol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AccelPedal2Vol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CrashInputFreq_Hz'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CrashInputDuty_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrakeSWGPIO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PsDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RLDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CentralDoorLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrakeLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TrunkHanSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SeatSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CrashSignalGPIO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HWID1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HWID2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HWID3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HWID4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
