function BTQD_outputs(varargin)
%===========$Update Time :  2025-06-26 11:12:04 $=========
disp('Loading $Id: BTQD_outputs.m  2025-06-26 11:12:04    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-06-26 11:12:04 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTQD_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTQD_PedalMapTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_GearActualPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TMRotateDirectionReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkingPawlPwrOn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkingPawlEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DRTransfer_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqSource_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUCtrlMdTQD_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepSpdReq_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepIND_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActTUpAIND_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RollRegTorReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RollingRegenEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUDemHiPosVal_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VehAcclLimitTG_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TorqLimDoorOpn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUEBSHHSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUEBSRd4BR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkingProtectWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkingProtectAction_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActDriveMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCU4PweLmtInd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_GearFlashIndDis_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_GearFlashInd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SpdLimSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EngModeEnDetTime_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EngModeEnDetEnd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EngModeDisDetTime_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EngModeDisDetEnd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LVchrgSvrMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActFRDoorOPSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActMDDoorOPSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActTDDoorOPSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_Function1Off_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_Function2Off_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_Function3Off_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_Function4Off_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_Function5Off_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FunctionOffSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ComboKeyEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ComboKeyPreEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VehSpdLimitTG_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUTMVehSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUVehSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverTqDem_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AfterAvailableTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TMTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqReductEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ADASDriverDemWhTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RealWhTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUBCMBuzzReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUEBSHBSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1ActDrvMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1WheelSlipdet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1EMotorSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1EMotorOvrerSpd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1EMotorPerformance_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1EBrakeTorqLow_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU2MaxTorqAvail_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU2MinTorqAvail_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EEC3NFricPercTorq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EEC3EMPressLoss_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ETC2ActDriveDirect_enum'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1PctTrqP4_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1PctTrqPekTrqP5_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1EMTquModeDrvBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1ActEMpTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1ActEMOutSftSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1ActEMpTrqHrls_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1ActMaxAvaEMRecpTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdIdleP1_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1PercTorqIdleP1_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdIdleP2_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1PercTorqIdleP2_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdIdleP3_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1PercTorqIdleP3_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdIdleP4_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1PercTorqIdleP4_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1PercTorqIdleP5_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdIdleP5_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMRefTorq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMMaxMEngOvrSP7_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMMaxMOvrTmt_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMReqSpdCtrlLoLmt_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMReqTrqCtrlLoLmt_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMReqSpdCtrlUpLmt_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMReqTrqCtrlUpLmt_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMExtRSCtrlUpLmt_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMMomOfInertia_kgpm2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMDefTrqLmt_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSupVarRTSC1MSG_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSupTSC1CtrlPG1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSupTSC1CtrlPG3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSupTSC1CtrlPG2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSupTSC1CtrlPG4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMSpdHdleP6_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EC1EMGainEndSpdGvn_gain'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetLocat_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetCtrlMth_enum'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetSpdIdleP1_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1PctTrqIdleP1_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1MaxRetSpdP2_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetSpdP2_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1MaxRetSpdP3_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1PctTrqP3_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RefRetTrq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetSpdPekTrqP5_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RC1RetSpdP4_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUDemLoNegVal_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUDemSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUGearSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TUpAIND_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ETC1ShiftrPgs_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVCU1RecuperHighSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1DrvDemEMRtapTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1RetSelNonEng_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMRC1SACtrlDev_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUHandBrk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUMCUFootBrk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
