function BDID_outputs(varargin)
%===========$Update Time :  2025-03-10 13:48:26 $=========
disp('Loading $Id: BDID_outputs.m  2025-03-10 13:48:26    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-10 13:48:26 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDID_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDID_VSS_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_RUNTM_s'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_MILDIST_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_WARMUPS_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_CLRDIST_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_APPD_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_APPE_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_MILTIME_min'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_CLRTIME_min'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_BATSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HEVBATT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_BATSOH_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBCellVoltMin_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBCellVoltMax_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVESSCHARGELIM_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVESSCHARGEACT_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVESSENER_Whps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_NUMPSATRIPSFLTMEMCLR_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBattCurr_Ahps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_PSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_IPSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_IPSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_CPSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_CPSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBNAH_Ahr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBNE_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_IGNCNTR_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_TNBCPSAR_Ahr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TNBCPSAL_Ahr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TNECPSAR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TNECPSAL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TEBPSAR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TEBPSAL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TGEOVCR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_TGEOVCL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_GECHGOVCDCR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_GECHGOVCDCL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_GECHGOVCACR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_GECHGOVCACL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSV2XENNONPSAR_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSV2XENNONPSAL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKER_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKEL_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ResetCDEODTR_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_CDEODTR_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_CDEODTL_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempPSAR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempPSAL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempOVCR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempOVCL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempOFFR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AvgBattTempOFFL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_QTYPSATRIPSR_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_QTYPSATRIPSL_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSCNTDODRNGR_cnt'  ,8,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSCNTDODRNGL_cnt'  ,8,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_ETMATOER_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ETMATOEL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ETMBTOER_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ETMBTOEL_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCPSARNGR_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCPSARNGL_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCCHGRNGR_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCCHGRNGL_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCOFFRNGR_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCOFFRNGL_s'  ,8,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_MAXBATTEMPL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_MINBATTEMPL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_AVGBATTEMPL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PROTOCOLID_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTTEMPRNGAXIS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSTIMESOCRNGAXIS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_RESSCNTSDODRNGAXIS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_CALID_cnt'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_ECUNAME_cnt'  ,20,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKERNumerator_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKELNumerator_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_BattTempPSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_BattTempPSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_OVCR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_OVCL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_OFFR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_OFFL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_AVGBATTEMPL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_VinCode_cnt'  ,17,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_STASUP_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_HEVMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_HVBATT_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_DIDModelVersion_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_DIDModelVersionChksum_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
