function BINP_CAN3_outputs(varargin)
%===========$Update Time :  2025-05-08 18:47:11 $=========
disp('Loading $Id: BINP_CAN3_outputs.m  2025-05-08 18:47:11    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-08 18:47:11 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidB2TMInfo_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VBattInfo1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VCurrentLimit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VFult132960_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VST1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VST2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VST4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidB2VST5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEWP1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidTMMCUSta1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidTMMCUSta2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidTMMCUSta3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2THVRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VBI1BattType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VAPlsDischgCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VAvaPlsChgCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VHVILFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VACChgConnSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VACChgNegRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VACChgPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VBMUHVSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VChgMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VChgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VDCChgConnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VDCChgN1RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VDCChgP1RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VMainNegRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VFaultCode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VFaultLv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VPackCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VPackInsideVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VRqHVPwrOff_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VMinTempPos_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_B2VCellMinVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EWPPEFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AtvDisChgEnFbk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUCtrlMdSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUIGBTEnFbk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorTrq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUFailGrade_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUTrqLimHi_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUTrqLimLo_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUDCCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUDCVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUFailCode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
