%===========$Update Time :  2024-04-01 11:13:40 $=========
disp('Loading $Id: dhp_var.m  2024-04-01 11:13:40    foxtron $      FVT_export_businfo_v2.0 2021-11-02')
%% Calibration Name, Units, Min, Max, Data Type, Comment
a2l_par('KDHP_EAPS1BADLow_pct', 	'pct',    0,    30,    'single',    '');
a2l_par('KDHP_EAPS1BADHigh_pct', 	'pct',    70,    120,    'single',    '');
a2l_par('KDHP_EAPS2BADLow_pct', 	'pct',    0,    30,    'single',    '');
a2l_par('KDHP_EAPS2BADHigh_pct', 	'pct',    30,    60,    'single',    '');
a2l_par('KDHP_EAPS1BADTime_s', 	'sec',    0,    10,    'single',    '');
a2l_par('KDHP_EAPS2BADTime_s', 	'sec',    0,    10,    'single',    '');
a2l_par('KDHP_EAPS2Scaler_gain', 	'gain',    0.4,    3,    'single',    '');
a2l_par('KDHP_EAPS2Offset_pct', 	'pct',    0,    30,    'single',    '');
a2l_par('KDHP_EAPS12Disagree_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS12DisagreeTime_s', 	'sec',    0,    10,    'single',    '');
a2l_par('KDHP_EAPSLearnDwLow_pct', 	'pct',    0,    50,    'single',    '');
a2l_par('KDHP_EAPSLearnDwHigh_pct', 	'pct',    0,    50,    'single',    '');
a2l_par('KDHP_EAPSLearnDwMAX_pct', 	'pct',    0,    50,    'single',    '');
a2l_par('KDHP_GetNRMBaseTime_s', 	'sec',    0,    10,    'single',    '');
a2l_par('KDHP_EAPSStableThrsh_pct', 	'pct',    0,    50,    'single',    '');
a2l_par('KDHP_EAPSStableTime_s', 	'sec',    0,    10,    'single',    '');
a2l_par('KDHP_EAPSLearnUpHigh_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPSLearnUpLow_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPSLearnUpOffset_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS1MINInitUpLim_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS1MINInitLowLim_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS2MINInitUpLim_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS2MINInitLowLim_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS1Min_pct_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KDHP_EAPS1Min_pct_ovrdval', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EAPS2Min_pct_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KDHP_EAPS2Min_pct_ovrdval', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_AcceleratorLoadScalr_gain', 	'gain',    0,    3,    'single',    '');
a2l_par('KDHP_EAPS1WT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS2WT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_DeadBand_pct', 	'pct',    0,    100,    'single',    '');
a2l_par('KDHP_EPEDPOSNUpLimit_pct', 	'pct',    0,    120,    'single',    '');
a2l_par('MDHP_HysOffset_Y_pct', 	'pct',    0,    120,    'single',    '');
a2l_par('ADHP_HysOffset_X_pct', 	'pct',    0,    120,    'single',    '');
a2l_par('KDHP_AccPedalDepressed_pct', 	'deg',    0,    20,    'single',    '');
a2l_par('KDHP_AccPedalReleased_pct', 	'deg',    0,    20,    'single',    '');
a2l_par('KDHP_ActAPSPosn_pct_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KDHP_ActAPSPosn_pct_ovrdval', 	'pct',    0,    120,    'single',    '');
a2l_par('KDHP_EAPS11OutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS21OutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS12OutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS22OutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS1AOutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPS2AOutWT_gain', 	'gain',    0,    1,    'single',    '');
a2l_par('KDHP_EAPSCRBadWDSP_pct', 	'pct',    0,    120,    'single',    '');

%% Monitored Signals
% Internal Signals %
a2l_mon('VDHP_EPEDPOSN_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS1RAW_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2RAW_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS1BAD_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS2BAD_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1NRM_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2NRM_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS1DIS_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2DIS_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPSWDSP_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EPEDLIND_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS1WT_gain', 	'gain',    0,    1,    'single',    '');
a2l_mon('VDHP_EAPS2WT_gain', 	'gain',    0,    1,    'single',    '');
a2l_mon('VDHP_EAPS1NRMStable_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1LearnInRange_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1LearnDwEnable_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPSLearnUpEnable_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1Learned_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS2NRMStable_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS2LearnInRange_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS2LearnDwEnable_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS2Learned_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1NRMDiff_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2NRMDiff_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_HysOffset_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_PedalIncreasing_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1MINInit_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2MINInit_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_Inc2DecPctMemorize_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_Inc2DecMemoryReset_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_Dec2IncPctMemorize_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_Dec2IncMemoryReset_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EPEDLINDMem_pct', 	'pct',    0,    120,    'single',    '');

%% Outputs Signals
% Outputs Signals %
a2l_mon('VDHP_ActAPSPosn_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_LowIdleAccPedal_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_AccPedalSWSta_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS12RangeSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VDHP_EAPCRBAD_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VDHP_EAPS1MIN_pct', 	'pct',    0,    120,    'single',    '');
a2l_mon('VDHP_EAPS2MIN_pct', 	'pct',    0,    120,    'single',    '');
