function BV2L_outputs(varargin)
%===========$Update Time :  2024-12-05 14:47:51 $=========
disp('Loading $Id: BV2L_outputs.m  2024-12-05 14:47:51    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-12-05 14:47:51 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BV2L_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VV2L_ReqOBCV2LEna_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_ReqV2LIVIPopup_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_ReqV2LIVIDisChrg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_ReqOBCExtrV2LEna_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_ReqOBCIntrV2LEna_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_HVPO120VGrpALDSt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VV2L_HVPO120VGrpBLDSt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
