function BINP_APM_outputs(varargin)
%===========$Update Time :  2024-04-26 13:15:10 $=========
disp('Loading $Id: BINP_APM_outputs.m  2024-04-26 13:15:10    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-04-26 13:15:10 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_APM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_PASDRMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDRML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDRCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDRCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDFMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDFML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDFCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASDFCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDRLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDRLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDFLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDFLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASAFCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASARMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASARML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASARCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASARCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASAFMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASAFML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PASAFCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaRCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSStaFCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_Chime_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SNSRLayout_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_StaFSya_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ModOperation_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSProgressPCT_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSRQDisplay_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSSWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSHWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSExitCondition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSAngleTarget_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSStaSystem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSVRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDecReq_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSDecReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSShiftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSSpeedCMD_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSVMCReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAASSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAASVMCReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
