function BHAL_CAN1_outputs(varargin)
%===========$Update Time :  2025-05-08 18:42:01 $=========
disp('Loading $Id: BHAL_CAN1_outputs.m  2025-05-08 18:42:01    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-08 18:42:01 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN1_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidACBTMSC10000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACAmbTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidACBTMSC10001_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACFanSpdSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidACBTMSC10004_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TM2BFaultCode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidACBTMSC50000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACTempSetSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidASC1A_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ASC1KneelingInfo_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEBC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABSFullyOper_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABSOffroadSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ASRBrakeCtrlAtc_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ASREngCtrlAtc_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ASRHillHolderSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ASROffroadSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ATCASRInfoSig_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AcltrInterlockSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AntiLBrakABSAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrakePedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EBSAmWarnLampSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EBSBrakeSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EBSRedWarnLampSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EngAuxShutdownSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EngDerateSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EngRetSel_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HaltBrakeSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RmAccelEnSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SACtrlBrakeCtrl_SA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TractCtrlOvrSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TrailerABSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TrailerABSWarnSig_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEBC2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FASpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RelaSpdFALWheel_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RelaSpdFARWheel_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEBC5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkTempeWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FndBrkUse_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HaltBrkMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HillHolderMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ParkBrkActuFAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_XBRAcltnLimit_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_XBRActtrlMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_XBRSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidECASDM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ECASAWarmLampSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEMC1EM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1Cnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1OvrCtrlMBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1OvrCtrlMDriv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1OvrCtrlMPriBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1ReqTorqHRlsBrk_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1ReqTorqHRlsDri_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1ReqTorqLimBrk_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EM1ReqTorqLimDriv_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidHRW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WhlSpeedFL_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrivDirF_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TransReqGear_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
