function BINP_CAN3_outputs(varargin)
%===========$Update Time :  2024-07-31 13:44:57 $=========
disp('Loading $Id: BINP_CAN3_outputs.m  2024-07-31 13:44:57    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 13:44:57 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidBMS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidCCU1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidCCU2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidCCU4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUF1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUF2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUR2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidShifter1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSChckSum1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSRolCnct1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVInVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVBattDet12V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCCurLm_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCVoltLm_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACChrgCurrDis_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBChrgPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBDrvPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBDrvPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBFullChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBIsoImpedenceN_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBIsoImpedenceP_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBSOH_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattPackVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattSOCDis_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RemainChrgTime_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_CellTempAvg_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBCellVoltMax_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBCellVoltMin_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBMTempMax_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBMTempMin_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MaxCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MaxCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MinCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MinCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS6CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMS6RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSChckSum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSRolCnct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSREADY_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn8_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChrgPlugSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ExtChrgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBContactorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBHVILErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPreheatPrecoolSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattReady4Pre_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVILSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_V2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CCU1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CCU1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCAuxVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCInVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCWakeup4Plugin_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CCU2CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CCU2RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCPluginSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCV2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACCurLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCAuxCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCHVCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUF1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUF1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrActvDmpDisabSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEDUDrtSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEDUOpratingSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEDURealTMTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEDURotateDirction_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEDUTqReqFbk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCU1Chksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCU1RolCnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUBAT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUDCBusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUDCBusVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUDischrgSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUIGNsta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMotorAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrRegenAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrTMSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrTMTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrTMid_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrTMiq_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUWarnF_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrCoolanttempReq_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrEOPSpdSet_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrFailcode1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrFailcode2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrFailcodehistory1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrFailcodehistory2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrLLCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrLLCflowReq_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrMCUTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrTMTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUR1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUR1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrActvDmpDisabSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUDrtSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUOpratingSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDURealTMTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDURotateDirction_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUTqReqFbk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCU1Chksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCU1RolCnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUBAT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDCBusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDCBusVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDischrgSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUIGNsta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMotorAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrRegenAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMid_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMiq_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrCoolanttempReq_cnt'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEOPSpdSet_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcode1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcode2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcodehistory1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcodehistory2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrLLCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrLLCflowReq_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Shifter1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_Shifter1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterCRC8_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterHandleCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterRC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
