function BBCM_outputs(varargin)
%===========$Update Time :  2024-08-27 16:21:19 $=========
disp('Loading $Id: BBCM_outputs.m  2024-08-27 16:21:19    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-27 16:21:19 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BBCM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VBCM_HornCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FRHaltBrakeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FRDisIntEmCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FROpenClosePBCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DoorStaSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BrakeLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ReverseLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrFogLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PosLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LSMLPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RSMLPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnLpLActiveCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnLpRActiveCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BBuzzerCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WasherCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrRmLampBrightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WelcomeDemoSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TgateHDSWLSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TgateHDSWRSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TgateSWLSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TgateSWRSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LTgateRelCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RTgateRelCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDDoorOpen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDDoorstate_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
