function BDHP_outputs(varargin)
%===========$Update Time :  2025-05-09 16:47:51 $=========
disp('Loading $Id: BDHP_outputs.m  2025-05-09 16:47:51    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-09 16:47:51 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDHP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDHP_ActAPSPosn_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_LowIdleAccPedal_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_AccPedalSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS12RangeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPCRBAD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS1MIN_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS2MIN_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_ResetPedalZeroPosStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS1NRM_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS2NRM_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS1BAD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS2BAD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS1RAW_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDHP_EAPS2RAW_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
