function BINP_CAN3_outputs(varargin)
%===========$Update Time :  2024-08-22 14:56:32 $=========
disp('Loading $Id: BINP_CAN3_outputs.m  2024-08-22 14:56:32    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-22 14:56:32 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidBMS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidBMS8_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidCCU1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidCCU2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUBR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMCUBR2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidShifter1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSChckSum1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSRolCnct1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailChrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPwrAvailDchrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACChrgCurrDis_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FireDetErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBChrgPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBDrvPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBDrvPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBFullChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBIsoImpedenceN_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBIsoImpedenceP_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBSOH_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattPackVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattSOCDis_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RemainChrgTime_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_CellTempAvg_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBCellVoltMax_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBCellVoltMin_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBMTempMax_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBMTempMin_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MaxCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MaxCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MinCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MinCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVInVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVBattDet12V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCCurLm_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCVoltLm_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSChckSum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSRolCnct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSREADY_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BMSWarn8_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChrgPlugSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DisChrgPlugErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ExtChrgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBChrgErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBContactorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBHVILErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBOvrTempErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBOvrTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBPreheatPrecoolSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVBattReady4Pre_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HVILSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_V2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MainRlyNegSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MainRlyPosSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCAuxCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCAuxVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCHVCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCInVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCDCVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCWakeup4Plugin_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCPluginSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCV2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_OBCACCurLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCUWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrActvDmpDisabSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUDrtSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUOpratingSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDURealTMTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDURotateDirction_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrEDUTqReqFbk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUBAT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDCBusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDCBusVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUDischrgSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUIGNsta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMotorAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrRegenAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMid_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMiq_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrCoolanttempReq_cnt'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcode1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcode2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcodehistory1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrFailcodehistory2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrLLCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrLLCflowReq_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCU3HWVer_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCU3SWVer_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrMCUTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrTMTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterCRC8_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterFailsta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterHandleCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ShifterRC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
