function BHAL_APM_outputs(varargin)
%===========$Update Time :  2024-04-26 13:11:47 $=========
disp('Loading $Id: BHAL_APM_outputs.m  2024-04-26 13:11:47    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-04-26 13:11:47 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_APM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_PASDRMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDRML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDRCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDRCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDFMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDFML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDFCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASDFCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDRLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDRLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDFLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDFLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASAFCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASARMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASARML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASARCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASARCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASAFMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASAFML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PASAFCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaRCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSStaFCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Chime_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SNSRLayout_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_StaFSya_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ModOperation_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSProgressPCT_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSRQDisplay_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSSWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSHWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSExitCondition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSAngleTarget_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSStaSystem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSVRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDecReq_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSDecReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSShiftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSSpeedCMD_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSVMCReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAASSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAASVMCReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
