function BVMC_outputs(varargin)
%===========$Update Time :  2024-08-28 09:23:04 $=========
disp('Loading $Id: BVMC_outputs.m  2024-08-28 09:23:04    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-28 09:23:04 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BVMC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VVMC_ACCCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCPedalOvrd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCCtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCMSASpdWar_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSACtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CruzWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSAWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CruzActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSAActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSSpeedCMD_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSShiftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCPedalOvrd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LongAcc_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASNegReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSStaSys_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSDecReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSDecReq_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LFWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RFWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LRWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RRWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RawWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LFWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RFWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LRWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RRWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_PredictVehSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LF4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RF4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LR4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RR4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActMaxSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActLFSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActRFSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActLRSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActRRSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltLWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltRWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_EstSlope_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RWDRDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_IMUEnaCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RDCEnSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActStESCYaw_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CAASCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CAASActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedGyroY_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ExtraMSACtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
