function BDKC_outputs(varargin)
%===========$Update Time :  2024-03-25 17:22:00 $=========
disp('Loading $Id: BDKC_outputs.m  2024-03-25 17:22:00    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-03-25 17:22:00 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDKC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDKC_DKCTimeSN_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCAuthSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecReVehData_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecRemotePW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPCommandToPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPDKeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPDKeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPDKeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPDKeyWelcome_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPDkeyShowIVI_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPKeyMiss_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPKeyMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCDecPUIDLowPower_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_TimeSNDKCFbk_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
