function BDID_outputs(varargin)
%===========$Update Time :  2025-05-26 11:04:17 $=========
disp('Loading $Id: BDID_outputs.m  2025-05-26 11:04:17    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-26 11:04:17 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDID_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDID_VSS_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_RUNTM_s'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_MILDIST_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_CLRDIST_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_APPD_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_APPE_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_NUMPSATRIPSFLTMEMCLR_cnt'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDID_PSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_PSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_IPSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_IPSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_CPSAR_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_CPSAL_sec'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKER_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKEL_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_ResetCDEODTR_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_CDEODTR_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_CDEODTL_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_QTYPSATRIPSR_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_QTYPSATRIPSL_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDID_PROTOCOLID_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_CALID_cnt'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_ECUNAME_cnt'  ,20,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKERNumerator_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_PKELNumerator_kphsqr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VDID_VinCode_cnt'  ,17,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_DIDModelVersion_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDID_DIDModelVersionChksum_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
