function BINP_CAN2_outputs(varargin)
%===========$Update Time :  2025-05-29 13:48:49 $=========
disp('Loading $Id: BINP_CAN2_outputs.m  2025-05-29 13:48:49    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-29 13:48:49 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN2_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidHMI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidIVI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidIVI2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidIVI3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMETER1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACAirIntMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACAirIntPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACAutoBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACFrDefogBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACRecycleBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACWindDirMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIACWindDirPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIAutoInterLightCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIBCMPostDefogBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIZLSetTMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIZLSetTPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIZRSetTMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HMIZRSetTPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLighLowBatAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLighSafetyAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightBrightnessSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightColorSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightDimInDarkSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightWlcmLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnACMaxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnACReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnSyncReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIAutoWipHSpdSWCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICLWinLockDoorSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICreateAccReqSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDelAccReqSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDrivingLockSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIEPSForceCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIFrTrunkUnlockReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILinkAccReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILinkAccSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILinkKeySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILocatedSTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILockSoundSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMirrorFoldedSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVISWCVibModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVISilentChrgAlertSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStoppingUnlockSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIWPTCSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIsigScreenReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LINKtoDrive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OpenDrOpenWdoSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PWCONTINUEUSE_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SmartEcoModeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_UserSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACChgCurSet_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMOFFRecButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ApproachUnlockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CDLLockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CDLUnlockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Distanceunit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FollowMeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_GPSLAT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_GPSLONG_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIACCAdaptiveSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIAirIntZ3Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICarWashModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIChargePortSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICreepSWReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATHeaterCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATFroEdgeHeightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATHeightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATMemory1Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATMemory2Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATMemoryOPTCLSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATReclineCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIDSEATSlideCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIFGSAirIntCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIFGSChCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIIONSWCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIISAOffsetSpd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVINightModeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPSEATHeaterCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPSEATReclineCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPSEATSlideCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGOpenHeight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPWModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPwrLockSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPwroffreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRRDefReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIReqV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVISWCRUndefinedSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStartChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStopChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITrailerCheckReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITrailerModeSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITriggerreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIUnlockChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIWIMAINSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LDrvControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LPasControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRLDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRRDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LightShowStartReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LightShowStopReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MFRDNBrightReq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PerdV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFogLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RollModeSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCADJBUTT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCLimitSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCV2LLimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgStop_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgbutt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChglimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SetUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TCSSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSCaliButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_WlcmLightMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigAirIntenZon1Req_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigDfrstReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigFaceReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigFootReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigRecircReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigSetTempZon1Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigSetTempZon2Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICLBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICLBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICRBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVICRBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIHMICustmiFunSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIHMICustmiKEYSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILBlowerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVILSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLFMostCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLFootLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLNapModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLReclinerCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLSeatLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLSldRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLSliderCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMLZeroGravityCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRFMostCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRFootLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRNapModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRReclinerCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRSeatLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRSldRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRSliderCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIMRZeroGravityCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRBlowerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVISnowModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIUserTakeOverAPSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIZon1WindDirSWReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_METERKPHCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
