function BBCM_outputs(varargin)
%===========$Update Time :  2024-09-23 12:34:34 $=========
disp('Loading $Id: BBCM_outputs.m  2024-09-23 12:34:34    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-09-23 12:34:34 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BBCM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VBCM_AntitheftSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateRemote_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HornCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AllDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMDoorLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AntitheftSeatFlod_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PsDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RLDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RRDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockSetting_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CrashDetd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DoorLockIND_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_Dimmer_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DimmerEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PosLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrFogLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BrakeLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ReverseLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMBuzzerReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TrunkRel_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateHDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrWiper_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WasherCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WiperFixMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SleepReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User1DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User1IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User2DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User2IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User3DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User3IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User4DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User4IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User5DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User5IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User6DrAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User6IPAmbLightBrightness_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User1AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User2AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User3AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User4AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User5AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_User6AmbLightColor_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LampPwr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SPTGDet_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APSOpenPTG_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FollowMe_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_IVIRST_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CountAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFSWTri_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorFlodPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FuelDoorPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFRDNBrightReq_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGInnerSW2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagHCrash_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDrvCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LPasCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LRLDCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LRRDCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APMDoorControlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ATCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_fUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_OutMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
