function BPMM_outputs(varargin)
%===========$Update Time :  2025-05-13 19:20:23 $=========
disp('Loading $Id: BPMM_outputs.m  2025-05-13 19:20:23    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-13 19:20:23 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BPMM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VPMM_SysPowerMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerUpState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerDownState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ChrgState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerUpFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerDownFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ChrgFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_IRCRlyClose_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_IGNRlyClose_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_BattHVDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCDCRlyDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CACRlyDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_MCUHVLoopDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_EHPSRlyDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ACHVLoopDem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVSysReady_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DrivelineRelease_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMDCDCEnableDem_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ActiveDischargeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerDownCompleted_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerUpComplete_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ExtTorquePrevent_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerUpInhibit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VCUMCUEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VCUMCUCtrlMd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VCUMCUFailRst_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVILFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMEACEnableDem_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMEHPSDemSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMEHPSEnableDem_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_EHPSIniFinish_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_EACEnableCompleted_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_AlcLockSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LostHVComActivePwrDown_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVBattLowInd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ChrgPowerUpFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ChrgBCUHVFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVFailureChkPass_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVILDetectFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVChrgPreActFinished_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_TrigRBuzeer_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_TrigRLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_TrigBrkLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCDCVolLowTO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LongIdleDetFinsh_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BLifeSig_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux1OnOff_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux2OnOff_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux3OnOff_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BMainPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BMainPosRlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BACPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BACPosRlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAirPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAirPosRlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BOilPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BOilPosRlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BDCDCPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BDCDCPosRlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux1RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux1RlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux2RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux2RlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux3RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux3RlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux4RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BAux4RlyFit_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BRsv1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_V2BRsv2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VCULife1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VCULife2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VSPFunc_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VSPIGNKeySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VSPReversed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VSPTurnRight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_VSPTurnLeft_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_FogTMSRlyCMD_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
