function BDKC_outputs(varargin)
%===========$Update Time :  2025-05-29 11:28:48 $=========
disp('Loading $Id: BDKC_outputs.m  2025-05-29 11:28:48    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-29 11:28:48 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDKC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDKC_DKCTimeSN_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCAuthSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_TimeSNDKCFbk_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDKC_PCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyMissSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_ShippingMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyNumSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DkeyShowIVISta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DkeyAreaRAPSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaSPTGSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB4Invalid_flg'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWBOnOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB3Invalid_flg'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB1Invalid_flg'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB2Invalid_flg'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB0Invalid_flg'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UIDBatVolt_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_CoordinateX_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_FDCSPTGDet_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_FDCSPTGOpen_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UIDLowPowerSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_CoordinateY_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_AllowSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyTypeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_CalDistance_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWBDetPTGArea_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_A0UWBEvent_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_ParkingModeCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_ReVehData_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB0Distance_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKeyWelcomeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB1Distance_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB2Distance_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB3Distance_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB4Distance_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_BLERSSI_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_BLEdcEvent_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB0FPP_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB1FPP_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB2FPP_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB3FPP_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWB4FPP_enum'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UWBDetArea_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_OutputPCMDModule_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_FDCDKCAllowSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_JudgeKeepUnlockZone_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
