function BHAL_CAN4_outputs(varargin)
%===========$Update Time :  2025-05-14 10:40:04 $=========
disp('Loading $Id: BHAL_CAN4_outputs.m  2025-05-14 10:40:04    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-14 10:40:04 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN4_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidZFRC1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ParkBrakeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZFRCE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AirPressureFC2_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMAutoLightSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMBrakeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMHBeamSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMHeadLpSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMLFTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMLightSensorVSta_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMPLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMRFTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMRFogLpSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMSeatbeltSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMWasherSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMWiperASSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMWiperHSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZFRBCMWiperLSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZRRCE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMAllDoorSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZRRCE1001_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AirPressurePC3_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AirPressureRC1_kPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FDCCHASSISVCUEACPressSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMCallingSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMLRTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMPLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMRRTurnLpCSta_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMSTOPSW2Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZRRBCMSTOPSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidzGWCANRr1C500_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCOutVolSta_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EACEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EACErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EACInvTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EHPSEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EHPSErrLvSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EHPSInvTempSta_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EHPSMotorSpdSta_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUACRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUDCDCEACEHPSHVLoopSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUDCDCEACEHPSPreRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUDCDCEACEHPSRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUHVILSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUMCUHVLoopSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUMCUPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUMCUPreRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDUSelfChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
