function BBCM_outputs(varargin)
%===========$Update Time :  2024-07-17 14:18:09 $=========
disp('Loading $Id: BBCM_outputs.m  2024-07-17 14:18:09    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-07-17 14:18:09 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BBCM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VBCM_AntitheftSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateRemote_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HornCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AllDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMDoorLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AntitheftSeatFlod_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DrDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PsDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RLDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RRDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockSetting_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrChargingDoorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CrashDetd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DoorLockIND_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CTDLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_Dimmer_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DimmerEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PosLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HBeam_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrFogLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BrakeLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ReverseLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RDRL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RBSD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RTurnLP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_BCMBuzzerReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrDefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TrunkRel_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TailgateHDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FrWiperH_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RrWiper_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WasherCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WiperFixMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SleepReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBreath6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightBrightness6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLightColor6_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LampPwr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_SPTGDet_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APSOpenPTG_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FollowMe_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_IVIRST_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_CountAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFSWTri_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MirrorFlodPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FuelDoorPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_MFRDNBrightReq_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PTGInnerSW2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagHCrash_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagFRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRLTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DiagRRTS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LDrvCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LPasCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LRLDCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LRRDCtrlCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_APMDoorControlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbFunEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbWelEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbDimEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLinkDriSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbPwrWarnEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbODAEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_LockAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_ATCtrl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_fUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_UserNow_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbFunENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbWelENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbDimENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbLinkDriStaFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbPwrWarnENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbODAENFlash_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbColorSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_AmbBrightnessSta7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_HazardIND_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_DimSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_PassSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FWipSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FWasSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
