function BINP_CAN1_outputs(varargin)
%===========$Update Time :  2025-04-28 15:35:04 $=========
disp('Loading $Id: BINP_CAN1_outputs.m  2025-04-28 15:35:04    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-04-28 15:35:04 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN1_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidABM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEPB1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEPS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidESC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidESC5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValideBST1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABM1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABM1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABMPassengerODSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABMRearPassengerCTRODSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABMRearPassengerLHODSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABMRearPassengerRHODSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AirBagFailCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChecksumABM1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CrashOutputSts_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DriverSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LifeCountABM1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PABSwitchCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RCenterSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RDriverSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RPsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TLHPsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TRHPsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPB1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPB1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DOASta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPB1RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBCarWashMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBErrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBExtApplyAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBExtReleaseAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPS1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPS1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DriIntend_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPSAOIControl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPSRC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPSTOIActivation_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPSTOIFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPSTOIUnavailable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EpasFailed_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SASAngle_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SASCAL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SASSpeed_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SASSpeedValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SASV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABSFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABSWnlmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVHActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVHFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmberWnlmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EBDActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EBDFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC1CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC1RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCBeepReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCOFFStatus_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCOfflmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCWnlmpSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrPTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrntAxlTrqReqDrv_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_GRADE_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HBBActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HBBFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HDDActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HDDFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HSAActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HSAFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PBAActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PBAFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RearAxlTrqReqDrv_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RedWnlmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrPTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TCSFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC5CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC5RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AEBAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ActBrkLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkDiscTempSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkPedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkPedalPosSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkSwV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC5CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESC5RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCADASSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCAPSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCStandstill_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrRBCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrntAxlTrqReqBrk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LatAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LatAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LongAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LongAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCPressure_bar'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MCPressureV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MeterIndVehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RearAxlTrqReqBrk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RrRBCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_YawRate_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_YawRateV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LowBrakeFluidSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_eBSTAmberWnlmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_eBSTBeepReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_eBSTRedWnlmpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
