%===========$Update Time :  2025-05-14 15:18:43 $=========
disp('Loading $Id: inp_dkc_var.m  2025-05-14 15:18:43    foxtron $      FVT_export_businfo_v2.0 2021-11-02')
%% Calibration Name, Units, Min, Max, Data Type, Comment
a2l_par('KINP_NFCDoorSta_flg_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_NFCDoorSta_flg_ovrdval', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_NFCLidASta_flg_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_NFCLidASta_flg_ovrdval', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_KeyFobAreaU16_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_KeyFobAreaU16_enum_ovrdval', 	'enum',    0,    65535,    'uint16',    '');
a2l_par('KINP_UIDButtonCmd_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UIDButtonCmd_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_BTConnectSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_BTConnectSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UIDBatVoltx1000_V_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UIDBatVoltx1000_V_ovrdval', 	'V',    0,    65535,    'uint16',    '');
a2l_par('KINP_DKCBTRSSI_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_DKCBTRSSI_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWB1Distance_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB1Distance_cm_ovrdval', 	'cm',    0,    65535,    'uint16',    '');
a2l_par('KINP_UWB2Distance_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB2Distance_cm_ovrdval', 	'cm',    0,    65535,    'uint16',    '');
a2l_par('KINP_UWB3Distance_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB3Distance_cm_ovrdval', 	'cm',    0,    65535,    'uint16',    '');
a2l_par('KINP_UWB4Distance_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB4Distance_cm_ovrdval', 	'cm',    0,    65535,    'uint16',    '');
a2l_par('KINP_UWB5Distance_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB5Distance_cm_ovrdval', 	'cm',    0,    65535,    'uint16',    '');
a2l_par('KINP_UWB1Power_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB1Power_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWB2Power_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB2Power_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWB3Power_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB3Power_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWB4Power_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB4Power_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWB5Power_dB_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB5Power_dB_ovrdval', 	'dB',    -128,    127,    'int8',    '');
a2l_par('KINP_UWBpositionX_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWBpositionX_cm_ovrdval', 	'cm',    -32728,    32767,    'int16',    '');
a2l_par('KINP_UWBpositionY_cm_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWBpositionY_cm_ovrdval', 	'cm',    -32728,    32767,    'int16',    '');
a2l_par('KINP_UWB1RangingSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB1RangingSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UWB2RangingSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB2RangingSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UWB3RangingSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB3RangingSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UWB4RangingSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB4RangingSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UWB5RangingSta_enum_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWB5RangingSta_enum_ovrdval', 	'enum',    0,    255,    'uint8',    '');
a2l_par('KINP_UWBRangingON_flg_ovrdflg', 	'flg',    0,    1,    'boolean',    '');
a2l_par('KINP_UWBRangingON_flg_ovrdval', 	'flg',    0,    1,    'boolean',    '');

%% Monitored Signals
% Internal Signals %

%% Outputs Signals
% Outputs Signals %
a2l_mon('VINP_DKCDecReVehData_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecRemotePW_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPCommandToBCM_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPCommandToPTG_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPDKeyAreaLockUnlock_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPDKeyAreaPS_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPDKeyAreaPTG_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPDKeyWelcome_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPDkeyShowIVI_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPKeyMiss_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VINP_DKCDecPKeyMode_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_DKCDecPUIDLowPower_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VINP_TimeSNDKCFbk_cnt', 	'cnt',    0,    4294967295,    'uint32',    '');
a2l_mon('VINP_DKCDecryptionFail_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VINP_NFCDoorSta_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VINP_NFCLidASta_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VINP_KeyFobAreaU16_enum', 	'enum',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UIDButtonCmd_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_BTConnectSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UIDBatVoltx1000_V', 	'V',    0,    65535,    'uint16',    '');
a2l_mon('VINP_DKCBTRSSI_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWB1Distance_cm', 	'cm',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UWB2Distance_cm', 	'cm',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UWB3Distance_cm', 	'cm',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UWB4Distance_cm', 	'cm',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UWB5Distance_cm', 	'cm',    0,    65535,    'uint16',    '');
a2l_mon('VINP_UWB1Power_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWB2Power_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWB3Power_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWB4Power_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWB5Power_dB', 	'dB',    -128,    127,    'int8',    '');
a2l_mon('VINP_UWBpositionX_cm', 	'cm',    -32728,    32767,    'int16',    '');
a2l_mon('VINP_UWBpositionY_cm', 	'cm',    -32728,    32767,    'int16',    '');
a2l_mon('VINP_UWB1RangingSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UWB2RangingSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UWB3RangingSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UWB4RangingSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UWB5RangingSta_enum', 	'enum',    0,    255,    'uint8',    '');
a2l_mon('VINP_UWBRangingON_flg', 	'flg',    0,    1,    'boolean',    '');
