function BINP_CAN7_outputs(varargin)
%===========$Update Time :  2024-08-22 14:56:52 $=========
disp('Loading $Id: BINP_CAN7_outputs.m  2024-08-22 14:56:52    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-22 14:56:52 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN7_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidDoorFr1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DoorFrDoorEmergencysta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DoorFrDooroperationsta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DoorFrDoorpositionsta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
