function BBCM_outputs(varargin)
%===========$Update Time :  2025-04-14 19:05:54 $=========
disp('Loading $Id: BBCM_outputs.m  2025-04-14 19:05:54    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-04-14 19:05:54 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BBCM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VBCM_FDCBCMLBeamCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMPLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMHBeamCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMSMKLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMSMKRCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMDVRSignalLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMDVRSignalRCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMBSDBuzzerCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMSLTLpCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMSRTLpCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMLTurnLpCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRTurnLpCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMStopINDCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMSTOPBALLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMInnerCallBellCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMCallBellCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMWiperHCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMWasherCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMWiperLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMLDRLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRDRLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRFLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_TurnLpPatternSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMFDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMMDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRoomLpAmbCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMLBSDRCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMLBSDYCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRBSDRCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRBSDYCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMEmExitSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_InnerBuzzerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMInnerBuzzerCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRoomLpAmbSetSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRoomLpSetSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMFRoomLpSetSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMFRoomLpCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMMRoomLpSetSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMMRoomLpCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRRoomLpSetSta_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRRoomLpCmd_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMHelpINDCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMOSDrOpenSWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMEmSVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMFDOpenSVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMFDCloseSVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMMDOpenSVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMMDCloseSVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMLTurnSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRTurnSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMRGearSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMBrakeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_FDCBCMTurnBuzzerENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_WakeUp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VBCM_KeepWakeUp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
