function BTPM_outputs(varargin)
%===========$Update Time :  2025-02-14 13:47:49 $=========
disp('Loading $Id: BTPM_outputs.m  2025-02-14 13:47:49    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-02-14 13:47:49 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTPM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTPM_LFBatWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFBatWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRBatWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRBatWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFWheelTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFWheelTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRWheelTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRWheelTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFWheelDebug_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRWheelDebug_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFWheelDebug_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRWheelDebug_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSResButtAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSCaliButtAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFPressIndi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFPressIndi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRPressIndi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRPressIndi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSWarnIndi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFWheelTmpIndi_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFWheelTmpIndi_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRWheelTmpIndi_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRWheelTmpIndi_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFS1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFS1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRS1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRS1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFS2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFS2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRS2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRS2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFS3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFS3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRS3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRS3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFS4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFS4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRS4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRS4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_CWheelTips_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_AutoLTips_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFSensorMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFSensorMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRSensorMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRSensorMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S1ID_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S2ID_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S3ID_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S4ID_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S1L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S3L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S4L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ALFin_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_IDLock_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_IDin_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S1WheelDebugALTU_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S2WheelDebugALTU_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S3WheelDebugALTU_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_S4WheelDebugALTU_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ID1messageALTU_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ID2messageALTU_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ID3messageALTU_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ID4messageALTU_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_Chkfin_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_SetIDLoc_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ChkStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LFPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RFPind_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_RRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkLFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkRFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkLRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkRRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkfinLFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkfinRFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkfinLRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WriteChkfinRRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_Flashchkdatavalid_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_Flashdatavalid_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_unlearnSfali_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_unlearnSfailvalid_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_Prepresstempvalid_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FlashS1ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FlashS2ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FlashS3ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FlashS4ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VTPM_FlashIDvalid_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_WritingCnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSTLCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_LProgress_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_TPMSSensorIDRegStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ModelVersion_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTPM_ModelVersionChksum_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
