function BINP_CAN2_outputs(varargin)
%===========$Update Time :  2024-08-22 14:56:25 $=========
disp('Loading $Id: BINP_CAN2_outputs.m  2024-08-22 14:56:25    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-22 14:56:25 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN2_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidIVI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidIVI2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidIVIP200_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidMETER1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLighLowBatAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLighSafetyAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightColorSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightDimInDarkSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AmbLightWlcmLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnACMaxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnACReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCPFrEvtBtnSyncReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LINKtoDrive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_OpenDrOpenWdoSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PWCONTINUEUSE_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SmartEcoModeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACChgCurSet_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMOFFRecButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CDLLockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CDLUnlockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Distanceunit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ESCSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FollowMeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_GPSLAT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_GPSLONG_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVINightModeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPWModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPwrLockSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPwroffreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRRDefReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIReqV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStartChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIStopChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVITriggerreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIUnlockChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIWIMAINSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LDrvControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LPasControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRLDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRRDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LightShowStartReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LightShowStopReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MFRDNBrightReq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PerdV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFogLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RollModeSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCADJBUTT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCLimitSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOCV2LLimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgStop_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgbutt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChglimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SchedChgwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SetUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TCSSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSCaliButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_WlcmLightMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigAirIntenZon1Req_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigDfrstReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigFaceReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigFootReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigRecircReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigSetTempZon1Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_sigSetTempZon2Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIFrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIPassengerdoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRrRmLampBrightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_IVIRrRoomlampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_METERKPHCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
