function BINP_CAN4_outputs(varargin)
%===========$Update Time :  2024-07-31 13:45:08 $=========
disp('Loading $Id: BINP_CAN4_outputs.m  2024-07-31 13:45:08    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 13:45:08 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN4_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidDKC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidDKC2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZDRPTG1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneDR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneDR2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneDR3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneDR4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneDR6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneFR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidGWZoneFR2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZoneDrSCP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZoneDrTHCM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZoneDrVCU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidZoneFrTHCM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCReVehData_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCRemotePW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PCommandToPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDKeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDKeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDKeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDKeyWelcome_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDkeyShowIVI_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PKeyMiss_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PKeyMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PUIDLowPower_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_EncryptionDATA063_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VINP_EncryptionDATA64127_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomNumberX_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTGRDILSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWDimSw_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWFWasSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWFWipSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWPassSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWRWasSWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWRWipIntSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CSWTurnSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_MIRRORFOLDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RLSLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RLSRainSnrWiperCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RLTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RWiperAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RWiperProtection_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SWCCANCELSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SWCResUpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SWCSetdownSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SWCmodeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LDrvValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LPasValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRLDValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRRDValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTGInnerSW2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrntPTCRearLeActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrntPTCRearRiActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FrntPTCRiActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FLTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FRTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FWiperAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FWiperProtection_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_COMPStatorSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_CompProEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrSCPSysErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SetSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZoneSpdCtrlMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BlowerErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SolarL_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SolarLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SolarR_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SolarRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceRr_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFaceRrErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootRr_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TFootRrErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Tevap_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TevapErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Tincar_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TincarErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrAuBoxPwrN1Curr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrAuBoxPwrN2Curr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrColumnSWFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrCtrlBDVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrCtrlTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrEOBDFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrIVIFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrInfoFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPMMLVOutPErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPMMLimpHomeActReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPMMSysErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPowerTemp1_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPowerTemp2_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrInformationSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrONA1Curr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrONA2Curr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrStdbyACurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrPwrWindowECUFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrStdAErrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrTHCMFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ZoneDrMalfunLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AGSErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BatInTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_BatInTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BatOutTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_COMPErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EACProtectEnable_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EWP3Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EXV1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EXV2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FanErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorInTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorInTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorOutTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MotorOutTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTHighP_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTHighPErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTHighTact_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTHighTactErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowP1_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowP1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowP2_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowP2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowT1_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowT1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowT2_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_PTLowT2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOTXVErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOV1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOV2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SOV3Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Tamb_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TambErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
