function BNMM_outputs(varargin)
%===========$Update Time :  2024-04-02 13:11:34 $=========
disp('Loading $Id: BNMM_outputs.m  2024-04-02 13:11:34    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-04-02 13:11:34 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BNMM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VNMM_AllCANTxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_NMmTxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_Awake_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VNMM_CSB_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_ErrorState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VNMM_NodeID_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VNMM_PNI_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_RptMsgReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_WakeUp_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VNMM_ActiveWU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VNMM_SysNMmSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VNMM_NetworkReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
