%===========$Update Time :  2024-08-09 11:55:58 $=========
disp('Loading $Id: pmm_cal.m  2024-08-09 11:55:58    foxtron $      FVT_export_businfo_v2.0 2021-11-02')

a2l_cal('KPMM_BattUpFailtime_s',     5); 
a2l_cal('KPMM_DCDCEnableFailtime_s',     2); 
a2l_cal('KPMM_BattDownFailtime_s',     2); 
a2l_cal('KPMM_MCUDisableFailtime_s',     2); 
a2l_cal('KPMM_DCDCDisableFailtime_s',     2); 
a2l_cal('KPMM_OBCDisableFailtime_s',     2); 
a2l_cal('KPMM_OffA2OffTime_s',     60); 
a2l_cal('KPMM_MCUDisChrgFailtime_s',     2); 
a2l_cal('KPMM_DoorSWHoldTime_s',     0.1); 
a2l_cal('KPMM_ChrgPlugHoldTime_s',     0.1); 
a2l_cal('KPMM_AllDoorClosedHoldTime_s',     0.1); 
a2l_cal('KPMM_DrivetrainSelect_enum',     1); 
a2l_cal('KPMM_DCDCVSET_V',     14.4); 
a2l_cal('KPMM_DCDCVoltAllowedRange_pct',     20); 
a2l_cal('KPMM_LVBattThd_V',     12); 
a2l_cal('KPMM_LVBattThd24V_V',     24); 
a2l_cal('KPMM_LVBattChktime_s',     10800); 
a2l_cal('KPMM_HVBattSOCThd_pct',     10); 
a2l_cal('KPMM_OBCPreChgChkFailtime_s',     2); 
a2l_cal('KPMM_BrakeSWHoldTime_s',     0.1); 
a2l_cal('KPMM_DCDCSetVoltFailtime_s',     2); 
a2l_cal('KPMM_DriverSafetyChkFailtime_s',     2); 
a2l_cal('KPMM_MLvSafetyFailtime_s',     2); 
a2l_cal('KPMM_PrechrgChkFailtime_s',     2); 
a2l_cal('KPMM_SafetyChkFailtime_s',     2); 
a2l_cal('KPMM_Antitheft_enum_ovrdval',     0); 
a2l_cal('KPMM_Antitheft_enum_ovrdflg',     0); 
a2l_cal('KPMM_PDKeySta_enum_ovrdval',     0); 
a2l_cal('KPMM_PDKeySta_enum_ovrdflg',     0); 
a2l_cal('KPMM_IVIPoweOffreq_flg_ovrdval',     0); 
a2l_cal('KPMM_IVIPoweOffreq_flg_ovrdflg',     0); 
a2l_cal('KPMM_IVITriggerreq_flg_ovrdval',     0); 
a2l_cal('KPMM_IVITriggerreq_flg_ovrdflg',     0); 
a2l_cal('KPMM_HVBSOCOffStaChkFailtime_s',     2); 
a2l_cal('KPMM_HVBSOCOFFCStaChkFailtime_s',     2); 
a2l_cal('KPMM_HVBSOCStbyChkFailtime_s',     2); 
a2l_cal('KPMM_LVBattChrgtime_s',     1800); 
a2l_cal('KPMM_FrMCUDischrgVolt_V',     60); 
a2l_cal('KPMM_RrMCUDischrgVolt_V',     60); 
a2l_cal('KPMM_SilentChrgReq_flg_ovrdflg',     0); 
a2l_cal('KPMM_SilentChrgReq_flg_ovrdval',     0); 
a2l_cal('KPMM_TMSpdMCUDisThrsh_rpm',     3000); 
a2l_cal('KPMM_HVSOCWarnThd_pct',     25); 
a2l_cal('KPMM_SeatSWHoldTime_s',     0.1); 
a2l_cal('KPMM_OFFStaByPassLVBatt_flg',     0); 
a2l_cal('KPMM_TimeSNAllowDiff_cnt',     4); 
a2l_cal('KPMM_PwrStaOFFCTO_s',     1800); 
a2l_cal('KPMM_PwrStaONTO_s',     1800); 
a2l_cal('KPMM_PwrUpChkFailtime_s',     12); 
a2l_cal('KPMM_MCUDischrgVolt_V',     60); 
a2l_cal('KPMM_Sched_ChgTO_s',     60); 
a2l_cal('KPMM_CANValidChkFailtime_s',     2); 
a2l_cal('KPMM_LVBattChkOKStdT_s',     60); 
a2l_cal('KPMM_PwrStaStdTO_s',     300); 
a2l_cal('KPMM_DrivetrainSelect_enum_ovrdval',     0); 
a2l_cal('KPMM_DrivetrainSelect_enum_ovrdflg',     1); 
a2l_cal('KPMM_APSAllowThd_pct',     3); 
a2l_cal('KPMM_PluginVehSpdThd_kph',     3); 
a2l_cal('KPMM_LVChrgCurrMthd_flg',     0); 
a2l_cal('KPMM_LVChrgHoldT_s',     600); 
a2l_cal('KPMM_SysBaseCurr_A',     10); 
a2l_cal('KPMM_HVSOCWarnTime_s',     15); 
a2l_cal('KPMM_PwrStaONTOPop_s',     180); 
a2l_cal('KPMM_IVIPwroffHoldTime_s',     0.1); 
a2l_cal('KPMM_SchedChgHoldTime_s',     0.1); 
a2l_cal('KPMM_PWCONTINUEHoldTime_s',     0.1); 
a2l_cal('KPMM_SilentChrgReqTO_s',     2); 
a2l_cal('KPMM_FirstLVCheckHoldT_s',     5); 
a2l_cal('KPMM_FDADC12VDetAccu_s',     5); 
a2l_cal('KPMM_FDADC24VDetAccu_s',     5); 
a2l_cal('KPMM_LVBattOFFSlpThd_mV',     11900); 
a2l_cal('KPMM_LVBattOFFSlpThd24V_mV',     23800); 
a2l_cal('KPMM_OFFLVBattChkRetry_cnt',     2); 
a2l_cal('KPMM_LVBattChkWakehold_s',     30); 
a2l_cal('KPMM_FDADC12VDetAccuIntval_s',     1); 
a2l_cal('KPMM_FDADC24VDetAccuIntval_s',     1); 
a2l_cal('KPMM_HVPwrStaHoldTime_s',     0.5); 
a2l_cal('KPMM_SysPwrDownDbns_s',     0.1); 
a2l_cal('KPMM_BattUpResetRty_cnt',     3); 
a2l_cal('KPMM_BattUpResetSW_flg',     0); 
a2l_cal('KPMM_BattUpResetTO_s',     1); 
a2l_cal('KPMM_BattUpRstDlyTO_s',     1); 
a2l_cal('KPMM_HoodOffChkFailtime_s',     2); 
a2l_cal('KPMM_HVBattSOCPwrDwnThd_pct',     20); 
a2l_cal('KPMM_DCDCVSETLVChrg_V',     14.9); 
a2l_cal('KPMM_LVChrgVSetSW_flg',     0); 
a2l_cal('KPMM_PCUPwrUpDelayTime_s',     2); 
a2l_cal('KPMM_PCUDCDCRlyEnByPassSW_flg',     0); 
a2l_cal('KPMM_PCUEHPSRlyEnByPassSW_flg',     0); 
a2l_cal('KPMM_PCUEACRlyEnByPassSW_flg',     0); 
a2l_cal('KPMM_PCUChkFailTime_s',     2); 
a2l_cal('KPMM_UserLeaveTChk_s',     10); 
a2l_cal('APMM_LVChrgLv_X_mV',     [11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200]);
a2l_cal('MPMM_LVChrgLv_Y_Lv',     [3 3 3 3 3 3 3 3 2 2 1]);
a2l_cal('APMM_LVChrgLv24V_X_mV',     [22400 22600 22800 23000 23200 23400 23600 23800 24000 24200 24400]);
a2l_cal('MPMM_LVChrgLv24V_Y_Lv',     [3 3 3 3 3 3 3 3 2 2 1]);
a2l_cal('APMM_LVBattChktime_X_enum',     [1 2 3]);
a2l_cal('MPMM_LVBattChktime_Y_s',     [8300 8300 4200]);
a2l_cal('APMM_LVBattChrgtime_X_enum',     [1 2 3]);
a2l_cal('MPMM_LVBattChrgtime_Y_s',     [2700 2700 2700]);
a2l_cal('APMM_EWP1Curr_X_c',     [0 130 250]);
a2l_cal('MPMM_EWP1Curr_Y_A',     [0 1 5]);
a2l_cal('APMM_EWP3Curr_X_c',     [0 130 250]);
a2l_cal('MPMM_EWP3Curr_Y_A',     [0 1 5]);
a2l_cal('APMM_CoolgFanActCurr_X_pct',     [0 15 35 60 80]);
a2l_cal('MPMM_CoolgFanActCurr_Y_A',     [0 2.5 5.2 12.5 21.5]);
