function BINP_SYS_outputs(varargin)
%===========$Update Time :  2024-06-07 16:41:36 $=========
disp('Loading $Id: BINP_SYS_outputs.m  2024-06-07 16:41:36    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-06-07 16:41:36 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_SYS_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CarModel1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CarModel2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_CarModel3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ECU1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ECU2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Major1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Major2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Minor1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Minor2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Patch1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Patch2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Country1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Country2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Variation_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Dash1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Change1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Change2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Dash2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA5_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA6_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA7_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SHA8_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AcoreReadyToSlp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PwrReq_OTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AllowMovThd_OTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EvccAplusPwrUpReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrivetrainSelect_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ReadFlashCorrect_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashAntitheft_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw1'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw2'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw3'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw4'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw5'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw6'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw7'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RandomnumberY_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashACModeMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFace_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFoot_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFrost_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFaceM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFootM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashCCUSyncSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashACForceOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashsigRecircSt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRecAutoFlg_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashAirIntenZone1M_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_Flashfdefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashsigSetTempZon1St_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashsigSetTempZon2StM_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashCountAlarm_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashMFSWTri_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashMirrorFlodPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashFuelDoorPos_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLockSetting_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashMFRDNBrightReq_pct'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashWiperFixMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashIVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AnyNMID_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CurrentNmState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_NvmProtectSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AuxBattVolmV_mV'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_Pedal1Ref5V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_Pedal2Ref5V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EAPS1MINMem_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EAPS2MINMem_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashHoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashTailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashCTDLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashTailgateHDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_NetworkReqCalled_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PmicBootReason_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_WisrBootReason_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashAPMDoorControlSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AcoreRebootCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DIDGetDynoMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN1BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN2BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN3BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN4BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN5BusOff_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_funAuto_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagDRLOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagFMHT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagFLTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagFRTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagRLTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_DiagRRTC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_USSConfig_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TireSize_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_APSFunConfig_raw8'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashfUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
