function BACC_outputs(varargin)
%===========$Update Time :  2025-05-26 17:42:11 $=========
disp('Loading $Id: BACC_outputs.m  2025-05-26 17:42:11    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-26 17:42:11 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BACC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VACC_CACOverrun_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACRunFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSSpdDemTimeout_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSEnTimeout_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSMotorDemSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSSpdCtrlMode_enum'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2AutoTracH_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2KneeCtrlMReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2NLvReqFA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2NLvReqRA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2LvCtrlModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2LA1PosCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2LA2PosCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2DamStiffReqFA_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2DamStiffReqRA_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2DamStiffReqLA_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2KneeReqFA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2KneeReqRA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2KneeReqLSide_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_ASC2KneeReqRSide_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACEnDemand_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACTempOverHigh_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACPresWarn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_CACPresReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSEnDemand_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_EHPSDisEnTimeout_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_DCDCEnDemamd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACSpdDemand_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_VCUEACpumpTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_VCUEACPressureSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACTempWarnInd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_EACPressWarnInd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VACC_AirPressureFDisp_kpa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_AirPressureRDisp_kpa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VACC_AirPressurePDisp_kpa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
