function BHAL_CAN2_outputs(varargin)
%===========$Update Time :  2024-08-22 14:52:29 $=========
disp('Loading $Id: BHAL_CAN2_outputs.m  2024-08-22 14:52:29    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-22 14:52:29 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN2_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidIVI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLighLowBatAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLighSafetyAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightColorSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightDimInDarkSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightWlcmLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACMaxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnSyncReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LINKtoDrive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OpenDrOpenWdoSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PWCONTINUEUSE_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SmartEcoModeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACChgCurSet_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMOFFRecButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLLockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLUnlockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Distanceunit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FollowMeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLAT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLONG_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVINightModeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPWModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwrLockSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwroffreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRRDefReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIReqV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStartChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStopChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITriggerreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIUnlockChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIWIMAINSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LightShowStartReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LightShowStopReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MFRDNBrightReq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PerdV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFogLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RollModeSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCADJBUTT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCLimitSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCV2LLimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgStop_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgbutt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChglimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SetUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TCSSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSCaliButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WlcmLightMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigAirIntenZon1Req_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigDfrstReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFaceReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFootReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigRecircReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon1Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon2Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVIP200_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIFrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPassengerdoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRrAtmoLampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRrRmLampBrightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRrRoomlampCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMETER1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_METERKPHCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
