function BHAL_CAN6_outputs(varargin)
%===========$Update Time :  2024-07-17 09:08:54 $=========
disp('Loading $Id: BHAL_CAN6_outputs.m  2024-07-17 09:08:54    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-17 09:08:54 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN6_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidFCM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCComfortBandLower_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCComfortBandUpper_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCJerkLowerLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCJerkUpperLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCObjDist_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCObjDstLvl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCObjRelSpd_mps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCRequiredAccel_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCTakeoverReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASACCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASAEBReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASAEBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASCAMSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASDBSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASFCWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASFCWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASFaultSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASFltWrnReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASForceIdle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASISASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLDWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLDWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLFCHandsOffWarning_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLFCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLFCWarnSound_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLKASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLaneModeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLaneModeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLanecurveL_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLanecurveR_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLanetypeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASLanetypeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASSLIFSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASSLIFSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASShftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASShftPosnReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASVehSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASWarningMsg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AEBVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CameraBlockage_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM1Checksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM1LifeCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCMACCmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCMLKAStrToqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCMLKATOIAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCMLKATOIFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ForceLowBeam_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HazardWarningReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ISAWarningMsg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LKAHODDisplayWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LKAHODSoundWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVDAACCStatusInformation_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVDADisabled_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVDAFailinfo_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVDAMuteSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVDAWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LeftTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RightTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TargetType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeGapLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFCM3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvDervLt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvDervLt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvDervRt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvDervRt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvLt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvLt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvRt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneCurvRt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneHeadAngLt_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneHeadAngLt2_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneHeadAngRt_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELaneHeadAngRt2_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELanePosLt_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELanePosLt2_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELanePosRt_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MELanePosRt2_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidSRR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRBSDWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRBSDWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRODAWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRODAWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
