%===========$Update Time :  2024-08-22 14:52:25 $=========
disp('Loading $Id: hal_can1_var.m  2024-08-22 14:52:25    foxtron $      FVT_export_businfo_v3.0 2022-09-06')
%% Calibration Name, Units, Min, Max, Data Type, Comment

%% Outputs Signals
% Outputs Signals %
a2l_mon('VHAL_CANMsgInvalidDCDCStatus1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_DCDCEnSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidDCDCStatus2_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_DCDCOutVol_V', 	'V',    0,    1000,    'single',    '');
a2l_mon('VHAL_CANMsgInvalidEACStatus1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_EACEnSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidEBC1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_ABSFullyOper_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ABSOffroadSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ASRBrakeCtrlAtc_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ASREngCtrlAtc_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ASRHillHolderSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ASROffroadSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_ATCASRInfoSig_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_AcltrInterlockSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_AntiLBrakABSAct_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_BrakePedalPos_pct', 	'pct',    0,    100,    'single',    '');
a2l_mon('VHAL_EBSAmWarnLampSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EBSBrakeSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EBSRedWarnLampSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EngAuxShutdownSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EngDerateSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EngRetSel_pct', 	'pct',    0,    100,    'single',    '');
a2l_mon('VHAL_HaltBrakeSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_RmAccelEnSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_SACtrlBrakeCtrl_SA', 	'SA',    0,    255,    'single',    '');
a2l_mon('VHAL_TractCtrlOvrSw_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_TrailerABSSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_TrailerABSWarnSig_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidEBC2_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_FASpeed_kph', 	'kph',    0,    250.9961,    'single',    '');
a2l_mon('VHAL_RelaSpdFALWheel_kph', 	'kph',    -7.8125,    7.8125,    'single',    '');
a2l_mon('VHAL_RelaSpdFARWheel_kph', 	'kph',    -7.8125,    7.8125,    'single',    '');
a2l_mon('VHAL_CANMsgInvalidEBC5_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_BrkTempeWarn_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_FndBrkUse_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_HaltBrkMode_enum', 	'enum',    0,    7,    'uint8',    '');
a2l_mon('VHAL_HillHolderMode_enum', 	'enum',    0,    7,    'uint8',    '');
a2l_mon('VHAL_ParkBrkActuFAct_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_XBRAcltnLimit_mps2', 	'mps2',    -12.5,    12.5,    'single',    '');
a2l_mon('VHAL_XBRActtrlMode_enum', 	'enum',    0,    15,    'uint8',    '');
a2l_mon('VHAL_XBRSysSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidEHPSStatus1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_EHPSEnSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidEMC1EM1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_EM1CS_enum', 	'enum',    0,    7,    'uint8',    '');
a2l_mon('VHAL_EM1Cnt_enum', 	'enum',    0,    7,    'uint8',    '');
a2l_mon('VHAL_EM1OvrCtrlMBrk_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EM1OvrCtrlMDriv_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EM1OvrCtrlMPriBrk_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EM1OvrCtrlMPriDriv_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_EM1ReqTorqHRlsBrk_pct', 	'pct',    0,    15,    'single',    '');
a2l_mon('VHAL_EM1ReqTorqHRlsDri_pct', 	'pct',    0,    15,    'single',    '');
a2l_mon('VHAL_EM1ReqTorqLimBrk_pct', 	'pct',    -125,    125,    'single',    '');
a2l_mon('VHAL_EM1ReqTorqLimDriv_pct', 	'pct',    -125,    125,    'single',    '');
a2l_mon('VHAL_CANMsgInvalidEPB1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_EPBParkingBrakeSta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_CANMsgInvalidPDUStatus1_flg', 	'flg',    0,    1,    'boolean',    '');
a2l_mon('VHAL_PDUDCDCRlySta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_PDUEACRlySta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_PDUEHPSRlySta_enum', 	'enum',    0,    3,    'uint8',    '');
a2l_mon('VHAL_PDUSelfChkSta_enum', 	'enum',    0,    3,    'uint8',    '');
