function BDDM_outputs(varargin)
%===========$Update Time :  2025-03-12 20:49:54 $=========
disp('Loading $Id: BDDM_outputs.m  2025-03-12 20:49:54    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-12 20:49:54 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDDM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDDM_C3BMS6RCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3BMS6CSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3BMS6LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3BMS1RCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3BMS1CSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3BMS1LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU1RCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU1CSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU1LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU2RCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU2CSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C3CCU2LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C1ABM1RCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C1ABM1CSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C1ABM1LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Lv1ErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Lv2ErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Lv3ErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Lv4ErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_BrkSWErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_BrkSWNoBacDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_KeyAuthDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ONtoRdyDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HVB4PreDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCU4PreDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DCDC4PreDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HVRlyCloDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_BMSRdyDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DCDCEnaDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HiLvSaChkDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MidLvSaChkDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUDisDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DCDCDisDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HVRlyOpDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUActDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_OBC4PreDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_IniLVLoDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LVSupLoDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LVSupHiDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LVInErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DrStSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FLDoorSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RLDoorSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FRDoorSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RRDoorSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HoodSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_TailgaSWDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EDriveSysErrVCUErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VehMalfunLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDDM_APS1SigOoRDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_APS2SigOoRDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_APSCorrErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUF1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUR1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Shifter1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC7NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC5NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EnterNewOperCyc_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DiagHCrashDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DiagFLTSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DiagFRTSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DiagRLTSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DiagRRTSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FMLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FMRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RCLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RMLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RMRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RCRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FLLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FLRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RLLUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RLRUSSDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM2NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM2RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM2CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM3NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM3RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM3CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM4NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM4CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM5NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM5CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ZoneSCPNoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_BMSSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCMACCSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FrMCUSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RrMCUSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_CCUSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ACCAccelCmdErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ACCMalfuncDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_CCMalfuncDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MSAMalfuncDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ISAMalfuncDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUF1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUR1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUF1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUR1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Shifter1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_Shifter1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC7RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC7CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC5RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESC5CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FrMCUTqErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RrMCUTqErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LFBatwarnDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RFBatwarnDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LRBatwarnDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RRBatwarnDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LFPressIndiDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RFPressIndiDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LRPressIndiDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RRPressIndiDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LFWheelTmpHighDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RFWheelTmpHighDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LRWheelTmpHighDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RRWheelTmpHighDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LFSensorFailDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RFSensorFailDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LRSensorFailDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_RRSensorFailDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_C1EPAS2LCDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_5vAPS1PwrErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_5vAPS2PwrErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPBLockTODTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPBUnlockTODTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LimpHomeActTmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EDriveSysErr_VCUErrTmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPBSigErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FCM1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ESCSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ShifterSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DrVCUNoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_FrVCUNoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ZoneDrSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_ZoneFrSigErrDetDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPS1NoComDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPS1RCErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPS1CSErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPSSigErrDTC_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DTCDetect_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EngagePFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_DisengagePFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCURAPSErrLv2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCURAPSErrLv3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EDriveSysErrShifterErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_PMMBattErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_LVSysErrPwrOutErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_HVRlyOpFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_MCUActDisFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCUBrkSWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCUFLDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCUFRDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCURLDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCURRDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_SysAllowReadySta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCUHoodSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_VCUTailgateSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1NoComCFS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1RCErrCFS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPB1CSErrCFS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDDM_EPBSigErrCFS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
