function BHAL_TPMS_outputs(varargin)
%===========$Update Time :  2024-08-29 17:57:56 $=========
disp('Loading $Id: BHAL_TPMS_outputs.m  2024-08-29 17:57:56    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-29 17:57:56 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_TPMS_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_TPMSDataIn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSPressure_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSTemp_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSPressureMi_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSCRC_crc'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSCRCCalc_crc'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSFAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSBattLow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChkStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChkLFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChkRFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChkLRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChkRRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLFWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRFWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashLRWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashRRWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FlashunlearnSfali_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_S1ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_S2ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_S3ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_S4ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Prepresstemptrust_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSSensorIDRegSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSTrigger_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
