function BSCP_outputs(varargin)
%===========$Update Time :  2024-07-31 11:42:27 $=========
disp('Loading $Id: BSCP_outputs.m  2024-07-31 11:42:27    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 11:42:27 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BSCP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VSCP_CAN4FDVCU1VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1BrkPedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1BrkPedalPosSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1MCPressure_bar'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1BrkSwV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1MCPressureV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1BrkSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1ApproachUnlockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVIPTGOpenHeight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVIISAOffsetSpd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVILocatedSTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN4FDDKC1IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CAN5FDCONN1SWCmodeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
