function BINP_DKC_outputs(varargin)
%===========$Update Time :  2025-03-04 21:13:27 $=========
disp('Loading $Id: BINP_DKC_outputs.m  2025-03-04 21:13:27    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-04 21:13:27 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_DKC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_DKCDecReVehData_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecRemotePW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPCommandToPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPDKeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPDKeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPDKeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPDKeyWelcome_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPDkeyShowIVI_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPKeyMiss_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPKeyMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecPUIDLowPower_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeSNDKCFbk_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCDecryptionFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_NFCDoorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_NFCLidASta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_KeyFobAreaU16_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_UIDButtonCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BTConnectSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_UIDBatVoltx1000_V'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VINP_DKCBTRSSI_dB'  ,1,  'int8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
