function BINP_CAN6_outputs(varargin)
%===========$Update Time :  2024-07-17 09:14:15 $=========
disp('Loading $Id: BINP_CAN6_outputs.m  2024-07-17 09:14:15    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-17 09:14:15 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN6_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidFCM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidFCM3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidSRR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCComfortBandLower_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCComfortBandUpper_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCJerkLowerLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCJerkUpperLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCObjDist_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCObjDstLvl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCObjRelSpd_mps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCRequiredAccel_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCTakeoverReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ACCVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASACCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASAEBReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASAEBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASCAMSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASDBSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASFCWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASFCWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASFaultSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASFltWrnReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASForceIdle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASISASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLDWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLDWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLFCHandsOffWarning_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLFCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLFCWarnSound_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLKASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLaneModeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLaneModeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLanecurveL_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLanecurveR_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLanetypeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASLanetypeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASSLIFSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASSLIFSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASShftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASShftPosnReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASVehSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ADASWarningMsg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AEBVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CameraBlockage_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCM1Checksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCM1LifeCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCMACCmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCMLKAStrToqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCMLKATOIAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FCMLKATOIFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ForceLowBeam_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HazardWarningReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ISAWarningMsg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_LKAHODDisplayWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LKAHODSoundWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVDAACCStatusInformation_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVDADisabled_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVDAFailinfo_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVDAMuteSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_LVDAWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LeftTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RightTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TargetType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TimeGapLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvDervLt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvDervLt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvDervRt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvDervRt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvLt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvLt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvRt_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneCurvRt2_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneHeadAngLt_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneHeadAngLt2_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneHeadAngRt_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELaneHeadAngRt2_radians'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELanePosLt_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELanePosLt2_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELanePosRt_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_MELanePosRt2_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_SRRBSDWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SRRBSDWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SRRODAWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SRRODAWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
