function BTHC_outputs(varargin)
%===========$Update Time :  2025-05-15 20:02:18 $=========
disp('Loading $Id: BTHC_outputs.m  2025-05-15 20:02:18    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-15 20:02:18 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTHC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTHC_FDCompCmd_rpm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV1Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV2Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOV3Cmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEXV1Cmd_step'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEXV2Cmd_step'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDSOTXVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFWVCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDTWVCmd_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrWPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CoolgFanActDuty_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDAGSCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP1Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP2Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDEWP3Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrLeAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDFrRiAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDRrAPTCHeatPwrCmd_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDBlowerCmd_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BatteryMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EDriveMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CabinMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUACLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUAutoLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUACMaxLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUSyncLampSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigAirIntenZon1St_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigWindDirZon1St_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigRecircSt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon1St_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon2St_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigClntTHvBattOut_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnSolarLeft_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigClntTHvBattIn_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnSolarRight_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigAmbAirT_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigCbnAirT_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACSubMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDRecyAutoCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CompDeltaU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Compe_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Blowere_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Vbase_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_BlowerI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2P_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2I_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2U_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV2e_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCP_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCI_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCU_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_APTCe_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1P_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1I_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1U_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EXV1e_K'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACModeMem_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Face_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Foot_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Frost_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FaceM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FootM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUSyncSts_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACForceOFF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_RecAutoFlg_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1M_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_fdefog_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigSetTempZon2StM_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigDfrstSt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCAirIntZ3Sta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLVentENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLVentENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCRVentENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCRVentENSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCMAPTCForceOFFSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Z1TUP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Z1TDN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Z2TUP_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_Z2TDN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSAirIntSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSChSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSAirIntCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSFuncSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSChCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSIONSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSIONCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCMPreWPTCHeatSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EWPBUflag1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EWPBUflag2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_EWPBUflag3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FaceMSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FootMSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_fdefogSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CCUSyncStsSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_sigRecircStSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_RecyAutoSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone1MSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_AirIntenZone3MSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_IONSWStaSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSChStaSet123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSChStaSet457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSAirIntStaSet123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSAirIntStaSet457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_LVentENSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CLVentENSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_RVentENSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CRVentENSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_LEVentModeStaSet123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_LEVentModeStaSet457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_REVentModeStaSet123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_REVentModeStaSet457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentZStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentZStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentZStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentZStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCLEVentYStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCLEVentYStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCREVentYStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCTHCCREVentYStaSet7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set5_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_SettempZon1Set7_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACModeSet123_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_ACModeSet457_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FACESet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FOOTSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FrostSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_LVentEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CLVentEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_RVentEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_CRVentEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSLearnCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTHC_FDCFGSFuncSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTHC_THSysErrlampReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
