function BINP_CAN1_outputs(varargin)
%===========$Update Time :  2024-08-22 14:56:17 $=========
disp('Loading $Id: BINP_CAN1_outputs.m  2024-08-22 14:56:17    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-22 14:56:17 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN1_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CANMsgValidDCDCStatus1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidDCDCStatus2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEACStatus1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEBC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEBC2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEBC5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEHPSStatus1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEMC1EM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidEPB1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CANMsgValidPDUStatus1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_DCDCOutVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EACEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABSFullyOper_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ABSOffroadSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ASRBrakeCtrlAtc_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ASREngCtrlAtc_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ASRHillHolderSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ASROffroadSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ATCASRInfoSig_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AcltrInterlockSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AntiLBrakABSAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrakePedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EBSAmWarnLampSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EBSBrakeSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EBSRedWarnLampSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EngAuxShutdownSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EngDerateSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EngRetSel_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_HaltBrakeSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_RmAccelEnSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_SACtrlBrakeCtrl_SA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_TractCtrlOvrSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TrailerABSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TrailerABSWarnSig_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FASpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RelaSpdFALWheel_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_RelaSpdFARWheel_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrkTempeWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FndBrkUse_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HaltBrkMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HillHolderMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_ParkBrkActuFAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_XBRAcltnLimit_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_XBRActtrlMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_XBRSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EHPSEnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1Cnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1OvrCtrlMBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1OvrCtrlMDriv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1OvrCtrlMPriBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1OvrCtrlMPriDriv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1ReqTorqHRlsBrk_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1ReqTorqHRlsDri_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1ReqTorqLimBrk_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EM1ReqTorqLimDriv_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_EPBParkingBrakeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUDCDCRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUEACRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUEHPSRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_PDUSelfChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
