function BDKC_outputs(varargin)
%===========$Update Time :  2025-04-21 16:07:33 $=========
disp('Loading $Id: BDKC_outputs.m  2025-04-21 16:07:33    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-04-21 16:07:33 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BDKC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VDKC_DKCTimeSN_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKCAuthSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_TimeSNDKCFbk_cnt'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyMissSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DkeyShowIVISta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_PCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DKeyWelcomeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyAreaSPTGSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_UIDLowPowerSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_DkeyAreaRAPSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_ParkingModeCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyNumSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_KeyTypeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VDKC_FDCDKCAllowSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
