function BINP_IMU_outputs(varargin)
%===========$Update Time :  2024-03-04 17:46:34 $=========
disp('Loading $Id: BINP_IMU_outputs.m  2024-03-04 17:46:34    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-03-04 17:46:34 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_IMU_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_MemOffsetGyroX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_MemOffsetGyroY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_MemOffsetGyroZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_MemOffsetAccX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_MemOffsetAccY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_MemOffsetAccZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingGyroX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingGyroY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingGyroZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingAccX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingAccY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VINP_SensingAccZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
