function BHAL_CAN6_outputs(varargin)
%===========$Update Time :  2023-05-24 15:32:51 $=========
disp('Loading $Id: BHAL_CAN6_outputs.m  2023-05-24 15:32:51    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2023-05-24 15:32:51 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN6_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CAN6CANMsgInvalidDiagFuncReqFT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToABM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToAPM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToBMS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToCCU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToDKC_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToDSEAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToEOPF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToEOPR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToEPAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToESC_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToFCM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToFUSION_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToHMI_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToIVI_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToMCUF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToMCUR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToMRR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToPBW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToPSEAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToPTG_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToSRRM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToShifter_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToTBOX_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToTelltale_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToZONEDR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToZONEFR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAN6CANMsgInvalidDiagPhysReqToeBST_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
