function BPSA_outputs(varargin)
%===========$Update Time :  2025-05-12 21:01:23 $=========
disp('Loading $Id: BPSA_outputs.m  2025-05-12 21:01:23    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-05-12 21:01:23 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BPSA_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VPSA_Keystatus_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPSA_PBtrig_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPSA_EmergencyShutDown_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPSA_AlcLockPass_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
