function BAPM_outputs(varargin)
%===========$Update Time :  2024-06-06 12:00:54 $=========
disp('Loading $Id: BAPM_outputs.m  2024-06-06 12:00:54    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-06-06 12:00:54 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BAPM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VAPM_VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_VehSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_FSOffSwTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ChrgPlugSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDRMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDRML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDRCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDRCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDFMR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDFML_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDFCR_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASDFCL_cm'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSDRLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSDRLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSDFLR_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSDFLL_cm'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASAFCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASARMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASARML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASARCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASARCL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASAFMR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASAFML_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_PASAFCR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaRCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFMR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFML_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFLR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFLL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFCR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_USSStaFCL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_Chime_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SNSRLayout_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_StaFSya_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ModOperation_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkPedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkPedalPosTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ActAPSPosn_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFRawWhlSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFRawWhlSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRRawWhlSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRRawWhlSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFRawWhlSpeedVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFRawWhlSpeedVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRRawWhlSpeedVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRRawWhlSpeedVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFWhlRotDirTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFWhlRotDirTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRWhlRotDirTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRWhlRotDirTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFPulseCountVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFPulseCountVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRPulseCountVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRPulseCountVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LFPulseCountTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RFPulseCountTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LRPulseCountTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_RRPulseCountTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ShifterHandleCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ShifterHandleCmdTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_DriIntend_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_DriIntendTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPSAOIControl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPSAOIControlTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASAngle_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASAngleTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASSpeed_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASSpeedTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASSpeedValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASSpeedValidTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASCAL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASCALTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_SASVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_GRADE_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_GRADETimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_YawRate_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_YawRateTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LatAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LatAccelTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LongAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LongAccelTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_MCPressure_bar'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_MCPressureTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_YawRateV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_YawRateVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LatAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LatAccelVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LongAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_LongAccelVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_MCPressureV_bar'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_MCPressureVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkSwStaTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkSwV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_BrkSwVTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ESCStandstill_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ESCStandstillTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ESCAPSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ESCAPSStaTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBExtReleaseAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBExtReleaseAvailTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBExtApplyAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBExtApplyAvailTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBErrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBErrStaTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_EPBStaTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMparkingcancelTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMparkingexcuteTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMParkingmodeTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_AVMErrSTATimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_IVIStatusTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_CAASSwTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_IVIScreenTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ABSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_ABSActiveTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_TCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_TCSActiveTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_DriverSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_DriverSeatBeltCmdTimeOut_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSProgressPCT_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSRQDisplay_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSSWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSHWVer_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSExitCondition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSAngleTarget_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSVRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_APSRqEPASCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VAPM_CAASSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
