function BHAL_IMU_outputs(varargin)
%===========$Update Time :  2024-03-05 14:38:33 $=========
disp('Loading $Id: BHAL_IMU_outputs.m  2024-03-05 14:38:33    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-03-05 14:38:33 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_IMU_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_MemOffsetGyroX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MemOffsetGyroY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MemOffsetGyroZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MemOffsetAccX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MemOffsetAccY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MemOffsetAccZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingGyroX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingGyroY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingGyroZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingAccX_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingAccY_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SensingAccZ_raw16'  ,1,  'int16'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
