function BVMC_outputs(varargin)
%===========$Update Time :  2025-03-12 20:49:30 $=========
disp('Loading $Id: BVMC_outputs.m  2025-03-12 20:49:30    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-12 20:49:30 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BVMC_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VVMC_FeatSetSpdFinal_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VehicleSpeed_mph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VehicleSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MeterIndSpeed_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MeterIndSpeedForCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VMCAEBCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VMCACCCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VMCCCCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_VMCMSACtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FeatArbitrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FeatReqSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_JerkPCT_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LimitPCT_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LFWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RFWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LRWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RRWhlSpeedRollAve_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FrontRearSlipRatioCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RearWhlSlipRatioCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_SingleWhlSlipRatioCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LatAccCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_SafetyCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_EstSlope_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_SPD2ACCAct_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AccCalcuPID_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ISOAccLimit_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ISODecLimit_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ISOJerkLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCRequiredAccel_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_DISCReqAcc_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FeatArbitrFinal_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActACCRequiredAccel_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LateralCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLKASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LKAStrToqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LKATOIFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LKATOIAct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASAEBReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASFaultSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AEBVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASDBSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASACCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCObjDist_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCObjRelSpd_mps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_TimeGapLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCJerkUpperLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCComfortBandUpper_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCJerkLowerLimit_mps3'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCComfortBandLower_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASVehSpdLim_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASShftPosnReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASShftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASForceIdle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_HazardWarningReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RightTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LeftTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASFCWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLDWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASFltWrnReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCObjDstLvl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ForceLowBeam_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCTakeoverReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASWarningMsg_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASCAMSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_TargetType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASSLIFSpdLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LKAHODDisplayWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LKAHODSoundWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLFCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLaneModeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLaneModeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASSLIFSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASISASta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLDWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASFCWMute_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLFCHandsOffWarning_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LVDADisabled_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LVDAMuteSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LVDAFailinfo_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LVDAWarning_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LVDAACCStatusInformation_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLFCWarnSound_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FCMACCmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLanetypeR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLanetypeL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLanecurveL_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASLanecurveR_raw32'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASAEBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FCMLDWRequest_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FCMLDWFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASNegReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCPedalOvrd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ADASWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AccPedalOvrdDISC_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RearTqRatio_rat'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_TimeGapCalcu_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCCtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CruzActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCPedalOvrd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CruzWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSACtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSAActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSAWhlTqReq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSSpeedCMD_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSShiftPosnReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSStaSys_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSDecReqA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSDecReq_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_APSReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LongAcc_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RawWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LFWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RFWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LRWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RRWhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_PredictVehSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LF4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RF4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_LR4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RR4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_4WhlSpdSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActMaxSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActLFSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActRFSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActLRSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActRRSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltLWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltRWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_AltWhlSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CCMSASpdWar_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_IMUEnaCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RWDRDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_MSAWhlTqActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_RDCEnSlideRate_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ActStESCYaw_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ACCOvrdMemTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CAASCtrlAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CAASActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_ExtraMSACtrlSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedAccX_G'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedAccY_G'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedAccZ_G'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedGyroX_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedGyroY_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_CalibratedGyroZ_Dps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_SetACCDisableAPS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCAPSVRqEPSCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCAPSAngleTarget_deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCAPSRqEPSCtrl_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCAngCtrlTqWtGn_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCDrInpTqBstAct_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCMaxAngCtrlOutTqLim_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VVMC_FDCVMCDrInpTqBstGn_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
