function BHAL_CAN1_outputs(varargin)
%===========$Update Time :  2024-07-31 13:43:26 $=========
disp('Loading $Id: BHAL_CAN1_outputs.m  2024-07-31 13:43:26    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 13:43:26 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN1_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidABM1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABM1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABM1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AirBagFailCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChecksumABM1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CrashOutputSts_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DriverSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LifeCountABM1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RCenterSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RDriverSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RPsngrSeatBeltCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEPAS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DriIntend_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPSAOIControl_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEPAS2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SASAngle_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SASCAL_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SASSpeed_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SASSpeedValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SASV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEPB1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DOASta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPBCarWashMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPBErrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPBExtApplyAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPBExtReleaseAvail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EPBSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC1CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC1RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrPTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntAxlTrqReqDrv_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RearAxlTrqReqDrv_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrPTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_VehSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRPulseCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRPulseCountV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRRawWhlSpeed_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRRawWhlSpeedV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRWhlRotDir_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ABSFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVHActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVHFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BTCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EBDActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EBDFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GRADE_Deg'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HBBActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HBBFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HDDActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HDDFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HSAActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HSAFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PBAFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TCSActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TCSFailed_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC5CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC5RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkSwSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkSwV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC5CRC8_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC5RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LatAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LatAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LongAccel_Gps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LongAccelV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCPressure_bar'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCPressureV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_YawRate_degps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_YawRateV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ActBrkLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCADASSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCAPSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCStandstill_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidESC7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC7CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC7RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkPedalPos_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkPedalPosSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC7CS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESC7RC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrRBCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntAxlTrqReqBrk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RearAxlTrqReqBrk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrRBCActive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFCM2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM2CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM2RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCRequiredAccel_mps2'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCVehHoldReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM2Checksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM2LifeCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFCM3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM3CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM3RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCObjDist_m'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCObjRelSpd_mps'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASForceIdle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM3Checksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM3LifeCount_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidFCM4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM4CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM4RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCSetSpeed_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACCSetSpeedDisp_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ADASACCSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCM4Checksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ForceLowBeam_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HazardWarningReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LeftTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RightTurnLightReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TargetType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TimeGapLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidSRR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRBSDWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRBSDWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRODAWarnL_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SRRODAWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
