function BINP_TPMS_outputs(varargin)
%===========$Update Time :  2024-08-29 16:58:20 $=========
disp('Loading $Id: BINP_TPMS_outputs.m  2024-08-29 16:58:20    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-29 16:58:20 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_TPMS_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_TPMSDataIn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSPressure_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSTemp_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSPressureMi_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSCRC_crc'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSCRCCalc_crc'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSFAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSBattLow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_LFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_RFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_LRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChkStorge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChkLFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChkRFID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChkLRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_ChkRRID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRSensorFail_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRWheelPSW_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRPindi_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRP20_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRWheelPress_raw8'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLFWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRFWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashLRWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashRRWheelTemp_C'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_FlashunlearnSfali_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_S1ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_S2ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_S3ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_S4ID_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VINP_Prepresstemptrust_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSSensorIDRegSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_TPMSTrigger_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
