function BPMM_outputs(varargin)
%===========$Update Time :  2024-06-27 17:30:40 $=========
disp('Loading $Id: BPMM_outputs.m  2024-06-27 17:30:40    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-06-27 17:30:40 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BPMM_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VPMM_PowerUpState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerDownState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerUpFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerDownFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ActiveDischargeReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCDCEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DCDCVoltSetpoint_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVBatCnctReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVSysReadyToCharge_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PowerSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVPwrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVPwrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_SysPowerMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_FrMCUEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_RrMCUEnaReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DrivetrainSelect_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_DrSeatSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrStaSelect_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrStaConstraint_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_TCountSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrUpReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrDownReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LowSOCWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_ReVehThdChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVSysErrPwrOutErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_EvccAplusPwrUpReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrStaONTOPopReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_IVIPwrStaONTOPopT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVChrgHoldTtimer_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVBattChrgTimeCnt_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_SilentChkAllowSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_TimerAllowSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_FDADC12VDetAvg_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMAllowECUSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVSilentChrgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVSilentChrgReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVSilentChrgLv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_LVBattChktime_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VPMM_SafetyChkMLv_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_SafetyChkHLv_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HVChrgPreActionErrSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_MCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_MCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CtrlFrPwrStbA1P_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CtrlFrRC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CtrlFrBMSCCUCIR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CtrlFrEDUINVERTER_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_HWResetSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_CtrlDrPwrStbA2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrStaTOSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PMMAllowNMSleep_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VPMM_Sched_ChgTOSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_PwrReq_OTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_OTAPwrReqOFFChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_OTAPwrReqStdChkSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VPMM_MCUDCBusMaxVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
