function BINP_GPIO_outputs(varargin)
%===========$Update Time :  2023-10-04 10:56:21 $=========
disp('Loading $Id: BINP_GPIO_outputs.m  2023-10-04 10:56:21    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2023-10-04 10:56:21 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_GPIO_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_AccelPedal1VolShortHigh_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal1VolShortLow_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal1Vol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal1VolValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal2VolShortHigh_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal2VolShortLow_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal2Vol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VINP_AccelPedal2VolValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrakeSWGPIO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HoodSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TailgateSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_DrDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_PsDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RRDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_RLDoorSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CentralDoorLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HazardSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_BrakeLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_TrunkHanSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_SeatSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CrashSignalGPIO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_HWID1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HWID2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HWID3_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VINP_HWID4_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
