function BHAL_CAN3_outputs(varargin)
%===========$Update Time :  2025-05-08 18:42:10 $=========
disp('Loading $Id: BHAL_CAN3_outputs.m  2025-05-08 18:42:10    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2025-05-08 18:42:10 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidB2TMInfo_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2THVRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VBattInfo1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VBI1BattType_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VCurrentLimit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VAPlsDischgCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VAvaPlsChgCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VFult132960_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VHVILFault_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VST1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VACChgConnSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VACChgNegRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VACChgPosRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VBMUHVSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VChgMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VChgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VDCChgConnSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VDCChgN1RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VDCChgP1RlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VMainNegRlySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VST2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VFaultCode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VFaultLv_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VPackCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VPackInsideVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VRqHVPwrOff_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VST4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VMinTempPos_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidB2VST5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_B2VCellMinVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidEWP1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EWPPEFault_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTMMCUSta1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AtvDisChgEnFbk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUCtrlMdSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUIGBTEnFbk_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorTrq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTMMCUSta2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUFailGrade_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUTrqLimHi_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUTrqLimLo_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidTMMCUSta3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUDCCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUDCVol_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUFailCode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
