function BHAL_CAN3_outputs(varargin)
%===========$Update Time :  2024-07-31 13:43:42 $=========
disp('Loading $Id: BHAL_CAN3_outputs.m  2024-07-31 13:43:42    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 13:43:42 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN3_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidBMS1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSChckSum1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSRolCnct1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailChrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailChrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailChrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailDchrg_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailDchrg30_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPwrAvailDchrg60_kW'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVInVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LVBattDet12V_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCDCCurLm_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCDCVoltLm_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACChrgCurrDis_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBChrgPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBDrvPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBDrvPwrTotal_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBFullChrgPwr_kWh'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBIsoImpedenceN_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBIsoImpedenceP_Megaohm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBSOH_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattPackVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattSOC_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattSOCDis_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RemainChrgTime_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CellTempAvg_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBCellVoltMax_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBCellVoltMin_mV'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBMTempMax_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBMTempMin_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MaxCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MaxCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MinCellTempNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MinCellVoltNum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS6CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMS6RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSChckSum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSRolCnct_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSREADY_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn5_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BMSWarn8_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChrgPlugSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ExtChrgSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBContactorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBHVILErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBPreheatPrecoolSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattReady4Pre_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVILSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_V2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidBMS7_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HVBattErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidCCU1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CCU1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CCU1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCAuxVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCInVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCDCCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCDCVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCPreCompleted_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCWakeup4Plugin_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RCCCU1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidCCU2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CCU2CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CCU2RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCACCurrInf_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCACVoltInf_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCFaultSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCPluginSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCV2LSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OBCACCurLim_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RCCCU2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidCCU4_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCAuxCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DCDCHVCur_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMCUF1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUF1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUF1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrActvDmpDisabSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEDUDrtSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEDUOpratingSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEDURealTMTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEDURotateDirction_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEDUTqReqFbk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCU1Chksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCU1RolCnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUBAT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUDCBusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUDCBusVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUDischrgSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUIGNsta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMotorAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrRegenAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrTMSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrTMTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrTMid_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrTMiq_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUWarnF_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMCUF2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrCoolanttempReq_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrEOPSpdSet_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrFailcode1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrFailcode2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrFailcodehistory1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrFailcodehistory2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrLLCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrLLCflowReq_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrMCUTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrTMTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMCUR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUR1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUR1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MCUWarnR_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrActvDmpDisabSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEDUDrtSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEDUOpratingSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEDURealTMTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEDURotateDirction_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEDUTqReqFbk_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCU1Chksum_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCU1RolCnt_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUBAT_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUDCBusCurr_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUDCBusVolt_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUDischrgSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUEnaSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUIGNsta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUReady_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUReady4Pre_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUSysSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMotorAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrRegenAvailTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrTMSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrTMTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrTMid_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrTMiq_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMCUR2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrCoolanttempReq_cnt'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrEOPSpdSet_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrFailcode1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrFailcode2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrFailcodehistory1_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrFailcodehistory2_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrLLCTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrLLCflowReq_Lpmin'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrMCUTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RrTMTempWarn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidShifter1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Shifter1CSErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Shifter1RCErr_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ShifterCRC8_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ShifterHandleCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ShifterRC_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
