function BINP_CAN6_outputs(varargin)
%===========$Update Time :  2023-05-24 15:38:09 $=========
disp('Loading $Id: BINP_CAN6_outputs.m  2023-05-24 15:38:09    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2023-05-24 15:38:09 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BINP_CAN6_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VINP_CAN6CANMsgValidDiagFuncReqFT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToABM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToAPM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToBMS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToCCU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToDKC_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToDSEAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToEOPF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToEOPR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToEPAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToESC_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToFCM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToFUSION_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToHMI_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToIVI_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToMCUF_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToMCUR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToMRR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToPBW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToPSEAT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToPTG_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToSRRM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToShifter_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToTBOX_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToTelltale_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToZONEDR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToZONEFR_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VINP_CAN6CANMsgValidDiagPhysReqToeBST_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
