function BHAL_CAN2_outputs(varargin)
%===========$Update Time :  2024-07-17 09:08:34 $=========
disp('Loading $Id: BHAL_CAN2_outputs.m  2024-07-17 09:08:34    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-17 09:08:34 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN2_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidHMI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACAirIntMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACAirIntPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACAutoBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACFrDefogBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACRecycleBtnCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACWindDirMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIACWindDirPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIZ1SetTMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIZ1SetTPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIZ2SetTMCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HMIZ2SetTPCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLighLowBatAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLighSafetyAlertSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightBrightnessSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightColorSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightDimInDarkSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightWlcmLightSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACMaxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnSyncReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICreateAccReqSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDelAccReqSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILinkAccReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILinkAccSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILinkKeySta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILocatedSTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILockSoundSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LINKtoDrive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OpenDrOpenWdoSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PWCONTINUEUSE_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SmartEcoModeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_UserSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ACChgCurSet_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMOFFRecButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ApproachUnlockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLLockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLUnlockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Distanceunit_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FollowMeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLAT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLONG_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIAirIntZ3Cmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIChargePortSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICreepSWReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATHeaterCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATFroEdgeHeightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATHeightCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATMemory1Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATMemory2Sta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATMemoryOPTCLSSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATReclineCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDSEATSlideCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIISAOffsetSpd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVINightModeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPSEATHeaterCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPSEATReclineCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPSEATSlideCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGOpenHeight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPWModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwrLockSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwroffreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRRDefReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIReqV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStartChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStopChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITrailerCheckReqSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITrailerModeSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITriggerreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIUnlockChgreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIWIMAINSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LightShowStartReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LightShowStopReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MFRDNBrightReq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PerdV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFogLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RollModeSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCADJBUTT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCLimitSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCV2LLimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgStart_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgStop_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgbutt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChglimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SetUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TCSSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSCaliButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WlcmLightMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigAirIntenZon1Req_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigDfrstReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFaceReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFootReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigRecircReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon1Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon2Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI3_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICLBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICLBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICRBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICRBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDrBlowerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDrBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIDrBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLFMostCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLFootLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLNapModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLReclinerCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLSeatLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLSldRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLSliderCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMLZeroGravityCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRFMostCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRFootLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRNapModeCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRReclinerCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRSeatLiftCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRSldRestoreCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRSliderCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIMRZeroGravityCmd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPsBlowerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPsBlowerYSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPsBlowerZSta_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRSEATventCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMETER1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_METERKPHCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ODOMETER_km'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
