function BSYS_outputs(varargin)
%===========$Update Time :  2025-03-10 13:48:45 $=========
disp('Loading $Id: BSYS_outputs.m  2025-03-10 13:48:45    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-10 13:48:45 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BSYS_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VSYS_HWVer1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_HWVer2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_HWVer3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_CarModel1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_CarModel2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_CarModel3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_ECU1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_ECU2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Major1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Major2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Minor1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Minor2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Patch1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Patch2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Country1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Country2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Variation_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Dash1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Change1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Change2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_Dash2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA3_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA4_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA5_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA6_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA7_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_SHA8_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_NvWriteReqRisingEdge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSYS_FdcSlpReqRisingEdge_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSYS_FdcSlpTime_sec'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VSYS_PmicBootReason_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_WisrBootReason_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VSYS_AcoreRebootCmdACK_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSYS_CurrentNmState_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_ECUGen1_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_ECUGen2_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_PmicBootPath_raw32'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VSYS_DrivingMode_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSYS_ModelYear_cnt'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
