function BHAL_CAN2_outputs(varargin)
%===========$Update Time :  2024-07-31 13:43:30 $=========
disp('Loading $Id: BHAL_CAN2_outputs.m  2024-07-31 13:43:30    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-07-31 13:43:30 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN2_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidIVI1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightColorSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AmbLightUserSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BrkAbnGoReadySW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DRAmbLightBrightnessSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACMaxReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnACReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPFrEvtBtnSyncReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FCPMidEvtBtnAutoReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IPAmbLightBrightnessSet_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILockSoundSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIOTAUpdSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LINKtoDrive_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OTACancelDLReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OTACompNTFYPres_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OTADLReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OTASuspendDLReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OTAUpdStartReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OpenDrOpenWdoSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PWCLOSEIMD_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PWCONTINUEUSE_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedOTAwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SmartEcoModeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_UpdCountdownCancel_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_UpdCountdownSkip_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_VehACModReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMErrSTA_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMOFFRecButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMParkingmode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingcancel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AVMparkingexcute_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ApproachUnlockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CAASSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLLockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CDLUnlockButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATantiset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATentryfunset_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ESCSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FSOffSw_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FollowMeSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLAT_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_GPSLONG_enum'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HeadLampSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_HoodLatchSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVICreepSWReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIISAOffsetSpd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVINightModeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGModeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGOpenHeight_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGStaSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPTGUSStaSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPWModeReq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwrLockSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIPwroffreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIRRDefReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIReqV2L_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIScreen_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIStatus_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITriggerreq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVIWIMAINSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDControlCommand_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MFRDNBrightReq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_OFFACMODE_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PSEATventreq_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PerdV2L_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RFogLampSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RollModeSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RoomLampMode_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOCV2LLimit_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgbutt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SchedChgwake_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SenstivityPosition_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SetUnlockSingle_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TCSSWCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSCaliButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TPMSResButt_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnSwTimeSet_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WalkawayLockSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigAirIntenZon1Req_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigDfrstReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFaceReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigFootReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigRecircReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon1Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_sigSetTempZon2Req_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidIVI6_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVILocatedSTA_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeCheck_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeDay_DAY'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeHour_hr'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMinute_min'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeMonth_MONTH'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeSecond_s'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_IVITimeYear_YEAR'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidMETER1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_METERKPHCalcu_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
