function BSCP_outputs(varargin)
%===========$Update Time :  2025-03-28 09:48:17 $=========
disp('Loading $Id: BSCP_outputs.m  2025-03-28 09:48:17    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-03-28 09:48:17 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BSCP_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VSCP_triggerBAM_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CFGEM1Ctrl_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CFGEM1BAMTSize_raw'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CFGEM1BAMTNum_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CFGEM1BAMRsv_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_CFGEM1BAMPGN_raw'  ,1,  'uint32'  ,-1, 'real' ,'Sample'};...
         {'VSCP_triggerDT_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte0_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte1_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte2_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte3_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte4_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte5_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte6_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VSCP_DTbyte7_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
