function BHAL_CAN4_outputs(varargin)
%===========$Update Time :  2024-08-28 15:35:23 $=========
disp('Loading $Id: BHAL_CAN4_outputs.m  2024-08-28 15:35:23    foxtron $ FVT_export_businfo_v3.0 2022-09-06')
%===========$Update Time :  2024-08-28 15:35:23 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_CAN4_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_CANMsgInvalidDKC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DKCReVehData_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PCommandToBCM_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PCommandToPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDKeyAreaLockUnlock_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDKeyAreaPS_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDKeyAreaPTG_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDKeyWelcome_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PDkeyShowIVI_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PKeyMiss_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PKeyMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PUIDLowPower_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidDKC2_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EncryptionDATA063_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EncryptionDATA64127_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RandomNumberX_enum'  ,1,  'uint64'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZ24C10000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Z24CHAAirPressureFC2Sta_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Z24CHAAirPressurePC3Sta_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Z24CHAAirPressureRC1Sta_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZ24CE1000_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Z24BCMFWiperASSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Z24BCMSeatBeltSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZONEDR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MIRRORFOLDSW_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RLTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RRTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RWiperAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RWiperProtection_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZONEDRVCU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BlowerErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrPMMLVOutPErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrPMMSysErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrSCPSysErrLmp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DrStdAErrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SolarL_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SolarLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SolarR_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SolarRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceRr_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFaceRrErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootL_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootLErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootR_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootRErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootRr_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TFootRrErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Tevap_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TevapErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Tincar_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TincarErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ZoneDrMalfunLevel_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZONEFR1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_ChargeInletLockSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CompProEN_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FLTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FRTurnLampC_mA'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FWiperAS_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FWiperProtection_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TrailerCheck_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TrailerModeSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidZONEFRVCU_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BatInTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BatInTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_BatOutTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_COMPErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EACProtectEnable_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EWP3Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EXV1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_EXV2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FanErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrPMMLimpHomeActReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorInTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorInTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorOutTemp_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_MotorOutTempErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTHighP_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTHighPErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTHighTact_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTHighTactErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowP1_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowP1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowP2_KPa'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowP2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowT1_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowT1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowT2_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTLowT2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOTXVErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOV1Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOV2Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SOV3Err_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_Tamb_C'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TambErr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidzGWAPTC1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntPTCLeActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntPTCRearLeActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntPTCRearRiActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FrntPTCRiActHeatPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidzGWCANFr1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_COMPActualPwr_W'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_COMPStatorSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_PTCActuPwrHSC6_enum'  ,1,  'uint16'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CANMsgInvalidzGWLINDr1_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWDimSw_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWFWasSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWFWipSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWPassSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWRWasSWSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWRWipIntSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_CSWTurnSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FAPWL01LINResponseError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvMotorRelayError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvMotorRippleError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LDrvValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasMotorRelayError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasMotorRippleError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LPasValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDMotorRelayError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDMotorRippleError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRLDValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDMotorRelayError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDMotorRippleError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_LRRDValWdwOpened_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RAPWL01LINResponseError_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RLSLampSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_RLSRainSnrWiperCmd_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCACCSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCCANCELSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCDistanceSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCDownSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCLKASta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCLeftSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCRegenUp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCResUpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCRightSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCSetdownSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCTripSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCUndefinedSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCUpSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCVRSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VHAL_SWCmodeSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
