function BTQD_outputs(varargin)
%===========$Update Time :  2024-08-22 15:23:01 $=========
disp('Loading $Id: BTQD_outputs.m  2024-08-22 15:23:01    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2024-08-22 15:23:01 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BTQD_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VTQD_GearActualPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkRequest_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PBWLockTO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PBWUnlockTO_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDem_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AfterAvailableTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AfterAvailableTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqSourceFr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqSourceRr_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUAvailBrkRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUAvailBrkRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_TqTargetShaftSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LimpHomeAct_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RollRegenEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EVDriveMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ShiftGearPosn_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PButtonSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrActvDmpDisabReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrRgnDecrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrRgnDecrSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriverWhlTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUActTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUActTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDURolRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDURolRgnTq_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUSpdValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUAvailBrkRgnTqV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUSpdValid_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUAvailBrkRgnTqV_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RgnAbnorSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PTCSPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrRgnPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrRgnPermSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExternalTqAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrIdcMin_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrIdcMax_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrUdcMin_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrUdcMax_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrIdcMin_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrIdcMax_A'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrUdcMin_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrUdcMax_V'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CoordWhlTqDemFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CoordWhlTqDemRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CrashDetd_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DiagHCrash_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ReBrakeLPReq_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_LowIdleAccPedal_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExtShftAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_BOSEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepON_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PreLoadHold_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_PreLoadPreEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CreepPrLoadEnable_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RDCActive_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ExtDoorAllow_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_WhlTqCapGenFr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_WhlTqCapGenRr_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RegenMode_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActEMpTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActMaxAvaEMRecpTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActDriveDirect_enum'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DLEngaged_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMTrqModeDrvBrk_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActEMpTrqHrls_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActEMOutSftSpd_rpm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DrvDemEMRtapTrq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_SACtrlDev_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RetSelNonEng_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ShiftPgs_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AccPedal1LowSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_AccPedalPos1_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ParkBrakeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_VCUVehSpd_kph'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_BrakeSW_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_NFricPercTorq_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EMParasLoss_pct'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EEC2MSGCnt_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EEC2MSGCS_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCCHAEBSRd4BRSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCCHAEBSHBSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCCHAEBSHHSwSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCVCUTUpAStaSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FDCVCUDACStatusSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_CoordTqDem_Nm'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_FrEDUSpRat_rat'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_RrEDUSpRat_rat'  ,1,  'single'  ,-1, 'real' ,'Sample'};...
         {'VTQD_EquivAccPedalSWSta_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_DriveProtEn_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_ActParkRequest_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
         {'VTQD_IVIPwrLockSta_enum'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VTQD_OPDHoldLamp_flg'  ,1,  'boolean'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
