function BHAL_DID_outputs(varargin)
%===========$Update Time :  2025-04-02 15:36:42 $=========
disp('Loading $Id: BHAL_DID_outputs.m  2025-04-02 15:36:42    foxtron $ FVT_export_businfo_v2.0 2021-11-02')
%===========$Update Time :  2025-04-02 15:36:42 $=========
% BXXX_outputs returns a cell array containing bus object information
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
% when the m-file is executed.
% The order of bus element attributes is as follows:
% ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
suppressObject = true;
elseif nargin > 1
error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
           {... 
    'BHAL_DID_outputs',...
       '', ...
       sprintf(''), { ... 
         {'VHAL_DIDStaXWDMode_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_XWDMode_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaDKCKey_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DKCKey_raw'  ,8,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaDynoMode_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DynoMode_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaTurnLampFRThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnLampFRThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaTurnLampRRThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnLampRRThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaTurnLampFLThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnLampFLThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaTurnLampRLThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TurnLampRLThreCurr_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaFMHTimer_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_FMHTimer_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaAutoLock_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AutoLock_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaDRLDis_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DRLDis_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaAutoWipHSpdEN_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_AutoWipHSpdEN_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaWipRLSCmdHoldFilter_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WipRLSCmdHoldFilter_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaWipRLSCmdCutFilter_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_WipRLSCmdCutFilter_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaUSSConfig_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_USSConfig_raw'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaTireSize_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_TireSize_raw'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_DIDStaAPSFunConfig_raw'  ,1,  'uint8'  ,-1, 'real' ,'Sample'};...
         {'VHAL_APSFunConfig_raw'  ,16,  'uint8'  ,-1, 'real' ,'Sample'};...
      } ... 
    } ...
  }'; 
if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
end
